### PR TITLE
Error from Qubit Released in Non-Zero State Causes Leak

### LINKED ISSUE #923: Error from Qubit Released in Non-Zero State Causes Leak
**Describe the bug**

When releasing a qubit in a non-zero state, a runtime error is thrown. This error may be causing a memory leak.

**To Reproduce**

Run the following code in the playground with 100 shots specified:
```qsharp
namespace input {
    @EntryPoint()
    operation Main() : Unit {
        use q = Qubit();
        H(q);
    }
}
```
You will see the shots become slower and slower.

**Expected behavior**

Shots should be run very fast.

**Additional context**

Similar code with the same runtime error does not have the perf issue:
```qsharp
namespace input {
    @EntryPoint()
    operation Main() : Unit {
        use q = Qubit();
        X(q);
    }
}
```

```qsharp
namespace input {
    @EntryPoint()
    operation Main() : Unit {
        use q = Qubit();
        H(q);
        M(q);
    }
}
```

### PR DESCRIPTION
**Pull request by swernli**
Fixes #923

### CODE REVIEW

**Review by ScottCarda-MS — APPROVED** [review]

File: compiler/qsc/src/interpret/stateful.rs [hunk 1]
```diff
@@ -264,7 +264,7 @@ impl Interpreter {
         };
 
         eval_expr(
-            &mut self.state,
+            &mut State::new(self.source_package),
```
Comment (cesarzc) [inline compiler/qsc/src/interpret/stateful.rs:267]: I'm curious about why a new state is created here rather than `self.state`.

File: vscode/src/webviewPanel.ts [hunk 2]
```diff
@@ -315,7 +315,7 @@ export function registerWebViewCommands(context: ExtensionContext) {
         await worker.run(code, "", parseInt(numberOfShots), evtTarget);
         clearTimeout(compilerTimeout);
       } catch (e: any) {
-        log.error("Codegen error. ", e.toString());
+        log.error("Histogram error. ", e.toString());
```
Comment (cesarzc) [inline vscode/src/webviewPanel.ts:318]: Was this just something you noticed but not exactly related to the fix?

File: wasm/src/tests.rs [hunk 3]
```diff
@@ -248,6 +248,36 @@ fn test_run_error_program_multiple_shots() {
     .assert_eq(&output.join("\n"));
 }
 
+#[test]
+fn test_run_error_program_multiple_shots_qubit_leak() {
+    // If qubits are leaked from execution, the runtime will fail with an out of memory
+    // error pretty quickly.
```
Comment (DmitryVasilevsky) [inline wasm/src/tests.rs:254]: I'm a bit hesitant about this "pretty quickly" statement. What if it hangs for a long time instead trying to come up with a memory? Maybe we can do something more deterministic...

File: compiler/qsc/src/interpret/stateful.rs (hunk 1 above)
Comment (swernli) [reply compiler/qsc/src/interpret/stateful.rs:267]: If there is an exception, we abort execution but do not clear the "tape" used to track execution. This means it can leave leftover expressions in the state that will cause failures on subsequent runs. We fixed a variation of this bug for Python at one point, but I missed it when implementing this variation and incorrectly reused the state from `self`. This works fine as long as execution completes, since that means the tape in the state gets fully evaluated.

File: wasm/src/lib.rs [hunk 4]
```diff
@@ -181,25 +181,27 @@ where
...
+            let msg = json!(
+                {"type": "Result", "success": false, "result": diag});
+            (out.event_cb)(&msg.to_string());
+            return Err(Box::new(e));
+        }
+    };
+
     for _ in 0..shots {
-        let result = interpreter.eval_entry(&mut out);
+        let result = interpreter.eval_entry_with_sim(&mut SparseSim::new(), &mut out);
```
Comment (cesarzc) [inline wasm/src/lib.rs:204]: Was the sparse simulator being used by default already when calling `eval_entry`?

File: compiler/qsc/src/interpret/stateful.rs (hunk 1 above)
Comment (swernli) [reply compiler/qsc/src/interpret/stateful.rs:267]: "Exception" is the wrong word... I mean a Q# runtime failure, like a divide by zero or an explicit `fail`, or in the sample case, a qubit released in a non-zero state.

File: vscode/src/webviewPanel.ts (hunk 2 above)
Comment (swernli) [reply vscode/src/webviewPanel.ts:318]: Yes. The dialog box that pops up on histogram execution failures had the wrong strong, and it made me thing I had run the wrong command!

File: wasm/src/tests.rs (hunk 3 above)
Comment (swernli) [reply wasm/src/tests.rs:254]: out of the 100 shots, I was seeing it fail around shot 24. Leaks are hard to be deterministic about... I suppose we could try peeking into the simulator state between shots to confirm it is the same?

File: wasm/src/lib.rs (hunk 4 above)
Comment (swernli) [reply wasm/src/lib.rs:204]: Yes, though it was reusing the one from the stateful interpreter rather than throwing it away between shots.

File: compiler/qsc/src/interpret/stateful.rs (hunk 1 above)
Comment (cesarzc) [reply compiler/qsc/src/interpret/stateful.rs:267]: I see, thank you for the explanation!

**Review by cesarzc — APPROVED** [review]

File: wasm/src/tests.rs (hunk 3 above)
Comment (swernli) [reply wasm/src/tests.rs:254]: I don't think I want to change how the test is invoked... the critical part of the change is that the undelrying API does the right thing with state between shot loops, and doing something like checking the state would require interrupting the loop to do other things in between. I'm going to leave this as-is, since it reliably reproduced the issue for us so far.

**Review by minestarks — APPROVED** [review]

File: compiler/qsc/src/interpret/stateful.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (swernli) [reply compiler/qsc/src/interpret/stateful.rs:267]: This is a good idea... I was joking with Ian that we are due for the semi-monthly evaluator/interpreter refactor ;). I think this change is something we should consider as part of a clean up after we've gotten some other things merged. For example, now that we have only the stateful interpreter, we can move it up a folder and get rid of the `stateful` module, which frees up the `stateful` name for use in some of our function names.
