### PR TITLE
Fix panic in QIR generation when conditional branches use early return

### LINKED ISSUE #2290: QIR Generation panics when conditional branches use early return
The following code causes a panic in QIR generation:

```qsharp
function Branch(value : Bool) : Int {
    if (value) {
        return 3;
    } else {
        return 4;
    }
}
@EntryPoint()
operation Main() : Int {
    use qubits = Qubit[2];
    H(qubits[0]);
    CNOT(qubits[0], qubits[1]);
    let result = Branch(MResetZ(qubits[0]) == Zero);
    result
}
```

However, the same code with implicit returns in the function works as expected:

```qsharp
function Branch(value : Bool) : Int {
    if (value) {
        3
    } else {
        4
    }
}
@EntryPoint()
operation Main() : Int {
    use qubits = Qubit[2];
    H(qubits[0]);
    CNOT(qubits[0], qubits[1]);
    let result = Branch(MResetZ(qubits[0]) == Zero);
    result
}
```

This appears to be because of how the `BranchControlFlow::Return` is used to short circuit the handling of the rest of the block:

https://github.com/microsoft/qsharp/blob/cd5c2e3b526ded2d01f589e9333890f3832ab6f0/compiler/qsc_partial_eval/src/lib.rs#L1837-L1839

This causes the generated RIR program to be missing branch and jump terminator instructions at the end of blocks. The empty block (should have one terminating jump) is what triggers the specific panic, but other non-empty blocks also are missing terminators that mean the program is invalid.

Either the early return should be fully handled by refactoring the control flow handling for dynamic branches (which must correctly handling inlining for functions like the example above) or the `RuntimeFeatureFlags::ReturnWithinDynamicScope` should be updated to require more than just `TargetCapabilityFlags::Adaptive` so that RCA rejects this pattern at compile time.

### PR DESCRIPTION
**Pull request by swernli**
This change avoids the panic in early returns by blocking them in RCA and providing the user with compile-time feedback before failing during QIR generation. It also includes updates to partial evaluation to ensure that the panicking case is now treated as a unimplemented graceful failure, since we don't have proper support for it.

Since QIR generation for programs with early return have never properly been handled, this doesn't take any functionality away but rather ensures earlier indication of the unsupported patterns at compile time. I filed #2387 to cover the additional work needed to fully support dynamic explicit returns.

Fixes #2290

### CODE REVIEW

File: compiler/qsc_partial_eval/src/tests/branching.rs [hunk 1]
```diff
@@ -2311,3 +2311,95 @@ fn if_expression_with_dynamic_operand_from_hybrid_doubles_array() {
                 Jump(6)"#]],
     );
 }
+
```
Comment (DmitryVasilevsky) [inline compiler/qsc_partial_eval/src/tests/branching.rs:2314]: We didn't have any "positive" tests for this, did we?

**Review by DmitryVasilevsky — APPROVED** [review]

File: compiler/qsc_partial_eval/src/tests/branching.rs (hunk 1 above)
Comment (swernli) [reply compiler/qsc_partial_eval/src/tests/branching.rs:2314]: We did not, because it turns out we never properly supported it. That's why it makes sense to reject it at compile time.
