### PR TITLE
The configured target is now passed to the debugger for compilation

### LINKED ISSUE #824: Debugger should respect selected execution profile
**Describe the bug**

When debugging a Q# program, the execution profile stays configured to `Full` even when `Base` is selected.

### PR DESCRIPTION
**Pull request by idavis**
Fixes #824

### CODE REVIEW

**Review by swernli — APPROVED** [review]

File: wasm/src/debug_service.rs [hunk 1]
```diff
@@ -31,12 +31,27 @@ impl DebugService {
...
             [(path.into(), source.into())],
             entry.as_deref().map(|value| value.into()),
         );
-        match Interpreter::new(true, source_map, qsc::PackageType::Exe, TargetProfile::Full) {
+        let target = match target_profile.as_str() {
+            "base" => TargetProfile::Base,
+            "full" => TargetProfile::Full,
+            _ => {
+                return render_error(qsc::interpret::stateful::Error::UnknownTarget(
+                    target_profile.to_string(),
```
Comment (minestarks) [inline wasm/src/debug_service.rs:50]: I think I'd rather sanitize this value before we call into WASM, and panic here if targetprofile is an invalid value. It doesn't feel worth adding a specific Interpreter error for, since getting the wrong value here would indicate a bug in _our_ code.

That being said, there are already 3 places where we read this value from settings and they all handle invalid values differently...

For display in the status bar, Defaults to "QIR:Invalid" for invalid value.
https://github.com/microsoft/qsharp/blob/b74867ceb788f490b95e6bb8a552faabc05c19ee/vscode/src/statusbar.ts#L58-L70

For configuring the language service, emits a warning but doesn't sanitize (this seems like a bug).
https://github.com/microsoft/qsharp/blob/b74867ceb788f490b95e6bb8a552faabc05c19ee/vscode/src/extension.ts#L228-L242

For QIR generation - just checks for "base" and ignores invalid values
https://github.com/microsoft/qsharp/blob/b74867ceb788f490b95e6bb8a552faabc05c19ee/vscode/src/qirGeneration.ts#L32-L33C13

This may be a good opportunity to refactor these into a utility function that sanitizes the value so we don't have to deal with handling invalid values everywhere?

File: npm/src/debug-service/debug-service.ts [hunk 2]
```diff
@@ -22,6 +22,7 @@ export interface IDebugService {
   loadSource(
     path: string,
     source: string,
+    target: string,
```
Comment (minestarks) [inline npm/src/debug-service/debug-service.ts:25]: It would be nice to strongly type this as "base" | "full" so that you force the caller to sanitize the value before calling. (See my other comment about this)

**Review by minestarks — APPROVED** [review]
