### PR TITLE
Fix language service panic when file isn't listed in the `files` field of `qsharp.json`

### LINKED ISSUE #2090: Creating a new .qs file in a project folder where the qsharp.json has files list triggers panic
When editing a Q# project that has an explicit files list in the qsharp.json, if you create a new .qs file in the src folder before adding it to the explicit files list the language service panics:
```text
2025-01-06 12:34:24.024 [error] [wasm] Wasm panic occurred: panicked at language_service/src/compilation.rs:297:14:
source should exist in the user source map

Stack:

Error: 
	at imports.wbg.__wbg_new_0232637a3cb0b1a7 (file:///Users/swernli/.vscode/extensions/quantum.qsharp-lang-vscode-dev-1.12.2/out/extension.js#vscode-extension:32866:17)
	at wasm://wasm/00e6c39a:wasm-function[3681]:0x312e28
	at wasm://wasm/00e6c39a:wasm-function[2061]:0x2c84c4
	at wasm://wasm/00e6c39a:wasm-function[2834]:0x2fe7b4
	at wasm://wasm/00e6c39a:wasm-function[2726]:0x2faeb5
	at wasm://wasm/00e6c39a:wasm-function[1851]:0x2a8fac
	at LanguageService.get_code_lenses (file:///Users/swernli/.vscode/extensions/quantum.qsharp-lang-vscode-dev-1.12.2/out/extension.js#vscode-extension:32709:12)
	at QSharpLanguageService.getCodeLenses (file:///Users/swernli/.vscode/extensions/quantum.qsharp-lang-vscode-dev-1.12.2/out/extension.js#vscode-extension:33815:33)
	at QSharpCodeLensProvider.provideCodeLenses (file:///Users/swernli/.vscode/extensions/quantum.qsharp-lang-vscode-dev-1.12.2/out/extension.js#vscode-extension:39781:51)
	at mf.provideCodeLenses (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:121:200273)
	at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:121:229194
	at Rt.s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:121:228034)
	at Rt.$provideCodeLenses (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:121:229182)
	at N0.S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:30:77539)
	at N0.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:30:77319)
	at N0.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:30:76370)
	at N0.L (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:30:75513)
	at tu.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:30:74310)
	at C.B (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:29:746)
	at C.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:29:964)
	at GN.e.port1.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/worker/extensionHostWorkerMain.js:145:3409)
```

Somehow this case should fail gracefully, ideally with feedback to the user that the file is not part of the project and won't be included in any compilation. Stretch goal could be a quick fix to put it into the files list from within that new file, but could also be just a warning that the file is not included (similar to how rust-analyzer does it).

### PR DESCRIPTION
**Pull request by minestarks**
Fixes #2090

Notably, this also changes how we treat the `files` field in `qsharp.json` for local projects their local dependencies.

Previously, if the `qsharp.json` explicitly listed any `files` , that list would take priority and we would skip crawling the directory.

With this change: we always crawl the `src/` directory and include all found `*.qs` files in the project. But we raise an explicit error to the user if any of those files are missing from the `files` list.

### CODE REVIEW

File: compiler/qsc_project/src/tests.rs [hunk 1]
```diff
@@ -436,7 +440,12 @@ fn explicit_files_list() {
                     packages: {},
                 },
                 lints: [],
-                errors: [],
+                errors: [
```
Comment (swernli) [inline compiler/qsc_project/src/tests.rs:443]: nitpick: I'd prefer duplicating the original test, leaving it as the "confirm no errors in good configuration" test and making the copy a test specific to this new error.

File: language_service/src/state/tests.rs
Comment (minestarks) [inline language_service/src/state/tests.rs:1]: Sorry about the unrelated changes. I changed how we format the test output in these files, so that they are readable and only include the information that the tests are concerned with.

I got fed up with the ridiculously long `Debug` outputs we had been using.

Comment (swernli) [reply language_service/src/state/tests.rs:1]: Righteous fix!

File: language_service/src/state/tests.rs [hunk 2]
```diff
@@ -1239,56 +740,218 @@ async fn update_doc_updates_project() {
...
-                    ),
+              uri: "project/src/this_file.qs" version: Some(1) errors: [
+                syntax error
+                  [project/src/this_file.qs] [we]
+              ],
+            ]"#]],
+    );
+}
+
+#[tokio::test]
```
Comment (minestarks) [inline language_service/src/state/tests.rs:758]: Here are the 2 new test cases, in case you have trouble finding it in the noise.

**Review by swernli — APPROVED** [review]

File: compiler/qsc_project/src/project.rs [hunk 3]
```diff
@@ -321,41 +380,37 @@ pub trait FileSystemAsync {
...
         directory: &Path,
+        errors: &mut Vec<Error>,
     ) -> ProjectResult<PackageInfo> {
         let manifest = self.parse_manifest_in_dir(directory).await?;
 
-        let manifest = ManifestDescriptor {
-            manifest_dir: directory.to_path_buf(),
-            manifest,
-        };
+        // For local packages, we include all *.qs files under the `src/`
```
Comment (ScottCarda-MS) [inline compiler/qsc_project/src/project.rs:392]: Is there a way to intentionally omit a local .qs file from being part of a project while leaving it under `src/`?

File: compiler/qsc_project/src/project.rs [hunk 4]
```diff
@@ -231,8 +234,64 @@ pub trait FileSystemAsync {
...
+        errors: &mut Vec<Error>,
+    ) {
+        qs_files.sort();
+        listed_files.sort();
+
+        let mut listed_files = listed_files.iter().peekable();
+
+        for item in qs_files.iter() {
+            while let Some(&next) = listed_files.peek() {
+                if next < item {
```
Comment (ScottCarda-MS) [inline compiler/qsc_project/src/project.rs:271]: I'm not understand this just at a glace. What does it mean to compare to PathBufs with a `<`?

File: language_service/src/state/tests.rs
Comment (ScottCarda-MS) [reply language_service/src/state/tests.rs:1]: Yah seems like a great fix to make the tests more readable!

**Review by ScottCarda-MS — APPROVED** [review]

File: compiler/qsc_project/src/project.rs (hunk 3 above)
Comment (minestarks) [reply compiler/qsc_project/src/project.rs:392]: With this change, there won't be.

File: compiler/qsc_project/src/project.rs (hunk 4 above)
Comment (minestarks) [reply compiler/qsc_project/src/project.rs:271]: Probably lexical comparison, but the implementation doesn't really matter here. The point is that I want to compare these to vectors item by item. And sorting them and iterating over both of them in the same order, was a practical way to do it. This `if` just skips over the items in `listed_files` iterator until it gets to one that it can compare with the current item in `qs_files` (next line).

File: compiler/qsc_project/src/project.rs [hunk 5]
```diff
@@ -231,8 +234,64 @@ pub trait FileSystemAsync {
...
     }
 
+    async fn collect_sources_from_files_field(
+        &self,
+        project_path: &Path,
+        manifest: &Manifest,
+    ) -> ProjectResult<Vec<PathBuf>> {
+        let mut v = vec![];
+        for file in &manifest.files {
+            v.push(
```
Comment (sezna) [inline compiler/qsc_project/src/project.rs:244]: just curious -- why this pattern instead of a `.map()`, as you suggested over in the import-package-command PR?

File: language_service/src/tests/test_fs.rs [hunk 6]
```diff
@@ -103,14 +103,17 @@ impl FsNode {
         let mut curr = Some(self);
         let mut curr_path = String::new();
         let mut last_manifest_dir = None;
-        let mut last_manifest = None;
 
+        // Traverse the path, keeping track of the last directory containing a
+        // manifest file. If we find a directory containing a manifest file and
+        // the next part of the path is "src", that's our manifest directory.
```
Comment (sezna) [inline language_service/src/tests/test_fs.rs:109]: is this a drive-by fix for nested projects?

**Review by sezna — APPROVED** [review]

**Review by sezna — APPROVED** [review]
Looks good, just left a few comments!

File: compiler/qsc_project/src/project.rs (hunk 5 above)
Comment (minestarks) [reply compiler/qsc_project/src/project.rs:244]: Good question, this code is old (I'm just moving it up from line 344 below), but I suspect it was because of the `await` and `?`  . Shoehorning a fallible, async function into `map()` might be possible but just looks awkward I think.

**Comment by fedimser** [comment]
Hello @minestarks!
Release of qsharp==1.13 broke build of our project without any changes on my side, and I beleive it's related to this PR.

On `init()`, we started getting this error for all source files, even though they all are explicitly listed in [qsharp.json](https://github.com/fedimser/quant-arith-re/blob/main/qsharp.json):
```
E       Exception: Qsc.Project.DocumentNotInProject
E       
E         x File src/EstimateUtils.qs is not listed in the `files` field of the
E         | manifest
E         help: To avoid unexpected behavior, add this file to the `files` field in
E               the `qsharp.json` manifest
E       
```

But **removing** all files from qsharp.json makes tests pass!

Does this mean we now are required to **not** list any .qs files if under src/ in the manifest? Or maybe there is a bug?

To reproduce this, you can clone [this repo](https://github.com/fedimser/quant-arith-re.git) and run `pytest .` from the root.

**Comment by swernli** [comment]
@fedimser Thanks for pointing us to the repo! I was able to try it in GitHub.dev (the extension works in the browser, even from the phone), and it looks like the project runs fine:
image

I wonder if it could be an issue with case sensitivity in the file system... are there any files or folders on your disk that are part of the project where the capitalization differs?

**Comment by fedimser** [comment]
The issue happens when you run `pytest .` , after `pip install qsharp==1.13`. Specifically, this happens in `qsharp.init()`. This happens both on my machine (Ubuntu) and on Github Actions, so I don't think it has to do with file names.

I tried to repro it on github.dev, but that would require installing `qsharp=1.13`, and the latest version available in that environment is `1.11.2.dev0`.

**Comment by swernli** [comment]
Ah, I will try to repro in a Python environment when I get the chance. 

For the available versions of the extension, depending on how your VS Code Web instance is configured it might not automatically update to the latest. If you use the "Install specific version" command then it will bring up the full list of versions for you to choose from:
image

**Comment by minestarks** [comment]
@fedimser  working on a fix. Really appreciate you letting us know!

**Comment by billti** [comment]
@fedimser we just shipped 1.13.2 which should address this. Please give it a try and let us know if you see any further problems. Thanks!

**Comment by fedimser** [comment]
Thank you! I verified that all tests pass when using `qsharp==1.13.2`.

Now there are 2 ways to have working Q# library: either explicilty list all sources in "files", or keep it empty. I assume explicilty listing all files is still the recommended way to do this, correct?

**Comment by swernli** [comment]
> Thank you! I verified that all tests pass when using `qsharp==1.13.2`.

Glad it works, @fedimser!

> Now there are 2 ways to have working Q# library: either explicilty list all sources in "files", or keep it empty. I assume explicilty listing all files is still the recommended way to do this, correct?

Not necessarily. The two ways of defining a library both work for local usage but have slightly different goals. When you skip including the `files` entry in the configuration file, the compiler will automatically search the local directory for any *.qs files under the src folder and include them in the project. However, if the project is intended to be used as a library dependency on GitHub for other projects, it _must_ include the `files` list because there is no "list all files in directory" option for folders pulled from GitHub. The wiki page on projects goes into some detail about the scenarios and their usage: [Q# External Dependencies (Libraries)](https://github.com/microsoft/qsharp/wiki/Q%23-External-Dependencies-(Libraries)). Hope that helps clarify!
