### PR TITLE
Strengthen check for inference type loops

### LINKED ISSUE #2426: Fuzz: "==5070== ERROR: libFuzzer: out-of-memory (used: 4204Mb; limit: 4096Mb)" (ubuntu-latest)
The fuzz-testing workflow has detected a bug.

<details><summary><b>Auto-Minimized Fuzzing Input That Triggers the Bug:</b> Click this line.</summary>
<b>Note:</b> If the input is multi-line then the end-of-line characters '\n' (0x0A) and '\r' (0x0D)
may affect the reproducibility of the bug. If you fail to repro the bug with the input shown below
then you may want to go to the <a href=https://github.com/microsoft/qsharp/actions/runs/15095461692>workflow</a> that reported this GitHub bug,
download the artifact, and extract the file with the exact minimized input.

```qs
operation a(){(foo,bar)->foo+bar=foo->foo
```

</details>

<details><summary><b>Fuzzing <code>stderr</code> Log</b> (last 62kB), includes the stack trace: Click.</summary>
The fragment of interest starts with "panicked at".

```gdb
Mb lim: 20000 exec/s: 563 rss: 178Mb L: 9379/20000 MS: 2 ChangeByte-EraseBytes-
#2588418	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 14436/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2588424	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3227/20000 MS: 1 EraseBytes-
#2588475	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 546/20000 MS: 1 EraseBytes-
#2588528	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 16314/20000 MS: 3 CopyPart-PersAutoDict-EraseBytes- DE: "Qubits"-
#2588685	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 5479/20000 MS: 2 ChangeBinInt-EraseBytes-
#2588706	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 420/20000 MS: 1 EraseBytes-
#2588722	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 10490/20000 MS: 1 EraseBytes-
#2588923	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 180/20000 MS: 1 EraseBytes-
#2589066	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1160/20000 MS: 3 ChangeBit-ChangeASCIIInt-EraseBytes-
#2589082	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2434/20000 MS: 1 EraseBytes-
#2589309	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 11620/20000 MS: 2 ChangeByte-CrossOver-
#2589337	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3027/20000 MS: 3 ShuffleBytes-ShuffleBytes-EraseBytes-
#2589639	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 7714/20000 MS: 2 PersAutoDict-EraseBytes- DE: "\001\000\000\000\000\000\036\000"-
#2589685	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 724/20000 MS: 1 EraseBytes-
#2589953	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 4845/20000 MS: 3 ChangeASCIIInt-ShuffleBytes-EraseBytes-
#2589974	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 696/20000 MS: 1 EraseBytes-
#2590020	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1377/20000 MS: 1 EraseBytes-
#2590276	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 514/20000 MS: 1 EraseBytes-
#2590450	REDUCE cov: 12640 ft: 75036 corp: 5920/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1351/20000 MS: 4 PersAutoDict-ChangeByte-InsertByte-EraseBytes- DE: "\001\000\000\000\000\000\0016"-
#2590557	REDUCE cov: 12640 ft: 75037 corp: 5921/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 17775/20000 MS: 2 ChangeBinInt-CrossOver-
#2590668	NEW    cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 893/20000 MS: 1 CopyPart-
#2590719	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5338/20000 MS: 1 EraseBytes-
#2590775	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 502/20000 MS: 1 EraseBytes-
#2590803	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5879/20000 MS: 3 CMP-ShuffleBytes-EraseBytes- DE: "\001\000\000i"-
#2591642	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 14642/20000 MS: 4 ChangeASCIIInt-CMP-InsertByte-EraseBytes- DE: "\377\377\377\377\377\377\000\011"-
#2591698	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 5/20000 MS: 1 EraseBytes-
#2591925	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3468/20000 MS: 2 InsertByte-EraseBytes-
#2592186	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 252/20000 MS: 1 EraseBytes-
#2592262	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1601/20000 MS: 1 EraseBytes-
#2592283	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3361/20000 MS: 1 EraseBytes-
#2592421	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 13600/20000 MS: 3 ChangeByte-CMP-EraseBytes- DE: "M\000\000\000\000\000\000\000"-
#2592533	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4001/20000 MS: 2 InsertByte-EraseBytes-
#2592839	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 247/20000 MS: 1 EraseBytes-
#2592895	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6532/20000 MS: 1 EraseBytes-
#2593081	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 98/20000 MS: 1 EraseBytes-
#2593332	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 149/20000 MS: 1 EraseBytes-
#2593338	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 264/20000 MS: 1 EraseBytes-
#2593389	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 198/20000 MS: 1 EraseBytes-
#2593565	REDUCE cov: 12640 ft: 75038 corp: 5922/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5408/20000 MS: 1 EraseBytes-
#2593716	REDUCE cov: 12640 ft: 75039 corp: 5923/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1792/20000 MS: 1 CopyPart-
#2593867	REDUCE cov: 12640 ft: 75039 corp: 5923/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 379/20000 MS: 1 EraseBytes-
#2594024	REDUCE cov: 12640 ft: 75039 corp: 5923/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2662/20000 MS: 2 PersAutoDict-EraseBytes- DE: "\000\000\000\000\000\000\000\023"-
#2594235	REDUCE cov: 12640 ft: 75039 corp: 5923/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3466/20000 MS: 1 EraseBytes-
#2594236	REDUCE cov: 12640 ft: 75041 corp: 5924/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7110/20000 MS: 1 CrossOver-
#2594378	REDUCE cov: 12640 ft: 75041 corp: 5924/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 937/20000 MS: 2 ChangeBit-EraseBytes-
#2594386	REDUCE cov: 12640 ft: 75041 corp: 5924/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 675/20000 MS: 3 ShuffleBytes-ChangeByte-EraseBytes-
#2594522	REDUCE cov: 12640 ft: 75041 corp: 5924/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 4148/20000 MS: 1 CrossOver-
#2594847	REDUCE cov: 12640 ft: 75041 corp: 5924/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 242/20000 MS: 5 ShuffleBytes-ChangeBinInt-CMP-PersAutoDict-EraseBytes- DE: "yarget"-"nt"-
#2595163	REDUCE cov: 12640 ft: 75041 corp: 5924/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 17770/20000 MS: 1 EraseBytes-
#2595579	REDUCE cov: 12640 ft: 75041 corp: 5924/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3989/20000 MS: 1 EraseBytes-
#2595611	NEW    cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 15815/20000 MS: 2 ChangeASCIIInt-CMP- DE: "body"-
#2595739	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1541/20000 MS: 3 InsertRepeatedBytes-ChangeByte-EraseBytes-
#2595820	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1775/20000 MS: 1 EraseBytes-
#2596011	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 10596/20000 MS: 1 EraseBytes-
#2596022	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 11756/20000 MS: 1 EraseBytes-
#2596088	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1683/20000 MS: 1 EraseBytes-
#2596195	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 215/20000 MS: 2 ChangeByte-EraseBytes-
#2596241	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 130/20000 MS: 1 EraseBytes-
#2596572	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 442/20000 MS: 1 EraseBytes-
#2596603	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 9230/20000 MS: 1 EraseBytes-
#2596749	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1112/20000 MS: 1 EraseBytes-
#2597293	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 4664/20000 MS: 4 ChangeBinInt-InsertByte-ChangeASCIIInt-EraseBytes-
#2597300	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 7021/20000 MS: 2 CopyPart-EraseBytes-
#2597657	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 400/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2597810	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2256/20000 MS: 3 ChangeBit-ChangeBinInt-EraseBytes-
#2598122	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 136/20000 MS: 2 ChangeByte-EraseBytes-
#2598234	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6464/20000 MS: 2 PersAutoDict-EraseBytes- DE: ")\000\000\000\000\000\000\000"-
#2598275	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 697/20000 MS: 1 EraseBytes-
#2598422	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1381/20000 MS: 2 ChangeByte-EraseBytes-
#2598503	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 437/20000 MS: 1 EraseBytes-
#2598649	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 297/20000 MS: 1 EraseBytes-
#2598856	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 5343/20000 MS: 2 InsertByte-EraseBytes-
#2598907	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 714/20000 MS: 1 EraseBytes-
#2598944	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 9947/20000 MS: 2 ShuffleBytes-EraseBytes-
#2599112	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 10314/20000 MS: 3 CMP-ChangeASCIIInt-EraseBytes- DE: "Intern"-
#2599371	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1440/20000 MS: 4 CopyPart-ChangeASCIIInt-ShuffleBytes-EraseBytes-
#2599557	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 10469/20000 MS: 1 EraseBytes-
#2599603	REDUCE cov: 12641 ft: 75042 corp: 5925/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 6987/20000 MS: 1 EraseBytes-
#2599731	REDUCE cov: 12641 ft: 75044 corp: 5926/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 11140/20000 MS: 3 CMP-CopyPart-CrossOver- DE: "Rxx"-
#2600218	REDUCE cov: 12641 ft: 75044 corp: 5926/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1189/20000 MS: 2 ShuffleBytes-EraseBytes-
#2600292	REDUCE cov: 12641 ft: 75044 corp: 5926/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 6708/20000 MS: 4 InsertByte-ChangeASCIIInt-InsertByte-EraseBytes-
#2600392	REDUCE cov: 12641 ft: 75044 corp: 5926/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3737/20000 MS: 5 ChangeBinInt-InsertRepeatedBytes-ChangeByte-ChangeBit-EraseBytes-
#2600443	REDUCE cov: 12641 ft: 75044 corp: 5926/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 227/20000 MS: 1 EraseBytes-
#2600541	REDUCE cov: 12641 ft: 75044 corp: 5926/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 13973/20000 MS: 3 InsertRepeatedBytes-CopyPart-CrossOver-
#2600655	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 10858/20000 MS: 4 EraseBytes-CMP-CrossOver-ShuffleBytes- DE: "9.23"-
#2600691	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 4888/20000 MS: 1 EraseBytes-
#2600712	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 5060/20000 MS: 1 EraseBytes-
#2601362	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 10916/20000 MS: 5 ShuffleBytes-CMP-CopyPart-ChangeBit-EraseBytes- DE: "\377\377\377\377\377\377\000\212"-
#2601408	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3579/20000 MS: 1 EraseBytes-
#2601645	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 8964/20000 MS: 2 InsertByte-EraseBytes-
#2601831	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2622/20000 MS: 1 EraseBytes-
#2601833	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3935/20000 MS: 2 ChangeBit-EraseBytes-
#2601840	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 563/20000 MS: 2 CMP-EraseBytes- DE: "4\000\000\000\000\000\000\000"-
#2602111	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 4251/20000 MS: 1 EraseBytes-
#2602212	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 5600/20000 MS: 1 EraseBytes-
#2602424	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2805/20000 MS: 2 ChangeBit-EraseBytes-
#2602460	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2699/20000 MS: 1 EraseBytes-
#2602576	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 843/20000 MS: 1 EraseBytes-
#2602607	REDUCE cov: 12642 ft: 75045 corp: 5927/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3216/20000 MS: 1 EraseBytes-
#2602766	REDUCE cov: 12642 ft: 75049 corp: 5928/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 11280/20000 MS: 4 ChangeBit-ChangeByte-CopyPart-CopyPart-
#2602882	REDUCE cov: 12642 ft: 75049 corp: 5928/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1089/20000 MS: 1 EraseBytes-
#2602908	REDUCE cov: 12642 ft: 75049 corp: 5928/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 16368/20000 MS: 1 EraseBytes-
#2602968	REDUCE cov: 12642 ft: 75049 corp: 5928/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 495/20000 MS: 5 ChangeByte-ChangeBinInt-InsertByte-ShuffleBytes-EraseBytes-
#2603039	REDUCE cov: 12642 ft: 75049 corp: 5928/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 5757/20000 MS: 1 EraseBytes-
#2603045	REDUCE cov: 12642 ft: 75049 corp: 5928/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7612/20000 MS: 1 EraseBytes-
#2603126	REDUCE cov: 12642 ft: 75049 corp: 5928/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1852/20000 MS: 1 EraseBytes-
#2603127	REDUCE cov: 12642 ft: 75049 corp: 5928/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1194/20000 MS: 1 EraseBytes-
#2603149	NEW    cov: 12642 ft: 75051 corp: 5929/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3348/20000 MS: 2 InsertRepeatedBytes-CopyPart-
#2603209	REDUCE cov: 12642 ft: 75051 corp: 5929/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 423/20000 MS: 5 ShuffleBytes-ChangeByte-InsertByte-ChangeBit-EraseBytes-
#2603275	REDUCE cov: 12642 ft: 75051 corp: 5929/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8421/20000 MS: 1 EraseBytes-
#2603278	REDUCE cov: 12642 ft: 75051 corp: 5929/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 897/20000 MS: 3 InsertByte-ChangeBinInt-EraseBytes-
#2603285	REDUCE cov: 12642 ft: 75051 corp: 5929/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 17337/20000 MS: 2 ChangeBit-EraseBytes-
#2603292	REDUCE cov: 12642 ft: 75051 corp: 5929/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 13478/20000 MS: 2 PersAutoDict-EraseBytes- DE: "\001\000\003("-
#2603452	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 19318/20000 MS: 5 ChangeASCIIInt-CMP-ChangeASCIIInt-ChangeByte-CopyPart- DE: "else"-
#2603513	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 776/20000 MS: 1 EraseBytes-
#2603613	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2400/20000 MS: 5 CMP-CopyPart-CopyPart-ChangeBinInt-EraseBytes- DE: "\013\000\000\000\000\000\000\000"-
#2603646	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1623/20000 MS: 3 PersAutoDict-ChangeBit-EraseBytes- DE: "\025\000\000\000\000\000\000\000"-
#2603692	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3188/20000 MS: 1 EraseBytes-
#2603839	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6559/20000 MS: 2 CMP-EraseBytes- DE: "\011\000\000\000\000\000\000\000"-
#2603976	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 8979/20000 MS: 2 ChangeBit-EraseBytes-
#2604129	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 6527/20000 MS: 3 CMP-ShuffleBytes-EraseBytes- DE: "borrow"-
#2604144	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 15776/20000 MS: 5 ChangeASCIIInt-PersAutoDict-PersAutoDict-PersAutoDict-EraseBytes- DE: "g\000\000\000"-"PrepareFxP"-"\014\000"-
#2604616	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1662/20000 MS: 2 InsertByte-EraseBytes-
#2604781	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3358/20000 MS: 5 ChangeASCIIInt-ShuffleBytes-InsertByte-PersAutoDict-EraseBytes- DE: "n\001\000\000"-
#2604860	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9479/20000 MS: 4 ChangeBit-ChangeBinInt-InsertByte-EraseBytes-
#2604981	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9235/20000 MS: 1 EraseBytes-
#2605173	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1812/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2605257	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 9878/20000 MS: 4 InsertByte-InsertByte-PersAutoDict-EraseBytes- DE: "\377\377\000\016"-
#2605448	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5720/20000 MS: 1 EraseBytes-
#2605456	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1245/20000 MS: 3 ChangeBinInt-CopyPart-EraseBytes-
#2605472	REDUCE cov: 12642 ft: 75052 corp: 5930/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 11122/20000 MS: 1 EraseBytes-
#2605549	NEW    cov: 12642 ft: 75053 corp: 5931/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12657/20000 MS: 2 CopyPart-CopyPart-
#2605620	REDUCE cov: 12642 ft: 75053 corp: 5931/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 6251/20000 MS: 1 EraseBytes-
#2605817	REDUCE cov: 12642 ft: 75053 corp: 5931/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 337/20000 MS: 2 ChangeBit-EraseBytes-
#2605919	REDUCE cov: 12642 ft: 75053 corp: 5931/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 995/20000 MS: 2 CrossOver-EraseBytes-
#2605975	REDUCE cov: 12642 ft: 75053 corp: 5931/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 16890/20000 MS: 1 CrossOver-
#2606036	REDUCE cov: 12642 ft: 75053 corp: 5931/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3334/20000 MS: 1 EraseBytes-
#2606204	NEW    cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 8817/20000 MS: 3 ShuffleBytes-ChangeBit-CopyPart-
#2606285	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 4472/20000 MS: 1 EraseBytes-
#2606292	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 5494/20000 MS: 2 ChangeByte-EraseBytes-
#2606577	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1351/20000 MS: 5 ChangeBinInt-ChangeBit-ChangeASCIIInt-ChangeByte-EraseBytes-
#2606783	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2953/20000 MS: 1 EraseBytes-
#2606845	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 8333/20000 MS: 2 InsertByte-EraseBytes-
#2606916	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 15150/20000 MS: 1 EraseBytes-
#2607182	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5124/20000 MS: 1 EraseBytes-
#2607188	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10602/20000 MS: 1 CrossOver-
#2607225	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 11301/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2607284	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3265/20000 MS: 4 CMP-EraseBytes-ChangeBinInt-CrossOver- DE: "Deprecated"-
#2607320	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 1128/20000 MS: 1 EraseBytes-
#2607532	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 324/20000 MS: 2 CrossOver-EraseBytes-
#2607533	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 16544/20000 MS: 1 EraseBytes-
#2607639	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2116/20000 MS: 1 EraseBytes-
#2607821	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 4496/20000 MS: 2 ChangeByte-EraseBytes-
#2607913	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 4743/20000 MS: 2 CMP-CrossOver- DE: "X\004\000\000\000\000\000\000"-
#2608094	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 382/20000 MS: 1 EraseBytes-
#2608270	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 403/20000 MS: 1 EraseBytes-
#2608451	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 386/20000 MS: 1 EraseBytes-
#2608462	REDUCE cov: 12642 ft: 75054 corp: 5932/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 597/20000 MS: 1 EraseBytes-
#2608519	REDUCE cov: 12642 ft: 75055 corp: 5933/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 18054/20000 MS: 2 ShuffleBytes-CopyPart-
#2608595	REDUCE cov: 12642 ft: 75055 corp: 5933/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 12464/20000 MS: 1 EraseBytes-
#2608605	REDUCE cov: 12642 ft: 75055 corp: 5933/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 3/20000 MS: 5 InsertByte-InsertByte-EraseBytes-EraseBytes-EraseBytes-
#2608756	REDUCE cov: 12642 ft: 75055 corp: 5933/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1227/20000 MS: 1 EraseBytes-
#2608787	REDUCE cov: 12642 ft: 75064 corp: 5934/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 18818/20000 MS: 1 CopyPart-
#2608870	REDUCE cov: 12642 ft: 75064 corp: 5934/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8316/20000 MS: 3 CopyPart-ChangeByte-CrossOver-
#2608931	REDUCE cov: 12642 ft: 75064 corp: 5934/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 239/20000 MS: 1 EraseBytes-
#2608966	REDUCE cov: 12642 ft: 75064 corp: 5934/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 2297/20000 MS: 5 ChangeASCIIInt-ChangeBinInt-EraseBytes-ChangeBit-ShuffleBytes-
#2608967	REDUCE cov: 12642 ft: 75064 corp: 5934/36Mb lim: 20000 exec/s: 563 rss: 178Mb L: 660/20000 MS: 1 EraseBytes-
#2609273	REDUCE cov: 12642 ft: 75064 corp: 5934/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12824/20000 MS: 1 EraseBytes-
#2609453	REDUCE cov: 12642 ft: 75064 corp: 5934/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3257/20000 MS: 5 ChangeASCIIInt-ChangeBinInt-PersAutoDict-PersAutoDict-EraseBytes- DE: "Cosh"-"\037\000\000\000\000\000\000\000"-
#2609499	NEW    cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 19636/20000 MS: 1 CopyPart-
#2609678	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 15768/20000 MS: 4 InsertRepeatedBytes-CopyPart-CMP-EraseBytes- DE: "\001\000\000\000\000\000\000\000"-
#2609704	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1266/20000 MS: 1 EraseBytes-
#2609726	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6053/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2609767	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5333/20000 MS: 1 EraseBytes-
#2610238	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 798/20000 MS: 1 EraseBytes-
#2610774	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 276/20000 MS: 1 EraseBytes-
#2610954	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8479/20000 MS: 5 ChangeByte-InsertByte-PersAutoDict-CMP-EraseBytes- DE: "\031\003\000\000"-"intrinsic"-
#2611003	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 491/20000 MS: 4 CopyPart-CopyPart-ChangeBinInt-EraseBytes-
#2611259	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 573/20000 MS: 1 EraseBytes-
#2611360	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4122/20000 MS: 1 EraseBytes-
#2611426	REDUCE cov: 12642 ft: 75065 corp: 5935/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 890/20000 MS: 1 EraseBytes-
#2611628	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10156/20000 MS: 2 InsertByte-CrossOver-
#2611811	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5455/20000 MS: 3 ChangeByte-ChangeBit-EraseBytes-
#2612087	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1857/20000 MS: 1 EraseBytes-
#2612127	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 895/20000 MS: 5 PersAutoDict-InsertRepeatedBytes-CrossOver-EraseBytes-CopyPart- DE: "andardTe"-
#2612368	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 16257/20000 MS: 1 CrossOver-
#2612439	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 13224/20000 MS: 1 EraseBytes-
#2612449	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1767/20000 MS: 5 ChangeASCIIInt-CopyPart-ChangeBinInt-CMP-EraseBytes- DE: "\020\000\000\000\000\000\000\000"-
#2612486	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4226/20000 MS: 2 CMP-EraseBytes- DE: "\001\021\000\000"-
#2612487	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9340/20000 MS: 1 EraseBytes-
#2612655	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10970/20000 MS: 3 ChangeASCIIInt-ChangeASCIIInt-EraseBytes-
#2612676	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 309/20000 MS: 1 EraseBytes-
#2612805	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1672/20000 MS: 4 ChangeBit-ChangeBinInt-ChangeByte-EraseBytes-
#2613087	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10883/20000 MS: 2 PersAutoDict-EraseBytes- DE: "-8"-
#2613403	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 18/20000 MS: 1 EraseBytes-
#2613454	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 364/20000 MS: 1 EraseBytes-
#2613570	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5496/20000 MS: 1 EraseBytes-
#2613901	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 940/20000 MS: 1 EraseBytes-
#2613939	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2398/20000 MS: 3 PersAutoDict-ChangeBinInt-EraseBytes- DE: "D\000\000\000\000\000\000\000"-
#2614165	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3891/20000 MS: 1 EraseBytes-
#2614216	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 13166/20000 MS: 1 EraseBytes-
#2614293	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1500/20000 MS: 2 CrossOver-EraseBytes-
#2614379	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3232/20000 MS: 1 EraseBytes-
#2614455	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1673/20000 MS: 1 EraseBytes-
#2614592	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 270/20000 MS: 2 CrossOver-EraseBytes-
#2614661	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7619/20000 MS: 4 CopyPart-CMP-PersAutoDict-EraseBytes- DE: "\\\000\000\000\000\000\000\000"-"Enumerated"-
#2614819	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 231/20000 MS: 3 ChangeBit-ShuffleBytes-EraseBytes-
#2614830	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 808/20000 MS: 1 EraseBytes-
#2614986	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9390/20000 MS: 1 EraseBytes-
#2615091	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4406/20000 MS: 5 ShuffleBytes-ShuffleBytes-InsertByte-CopyPart-EraseBytes-
#2615102	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1525/20000 MS: 1 EraseBytes-
#2615254	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1374/20000 MS: 2 PersAutoDict-EraseBytes- DE: "\001\000\000\000\000\000\000\005"-
#2615388	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4060/20000 MS: 4 ChangeASCIIInt-ChangeByte-ShuffleBytes-EraseBytes-
#2615655	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5195/20000 MS: 2 CMP-EraseBytes- DE: "\022\000\000\000"-
#2615666	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1568/20000 MS: 1 EraseBytes-
#2615721	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 210/20000 MS: 5 ChangeBit-InsertByte-CopyPart-ShuffleBytes-EraseBytes-
#2616002	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 566/20000 MS: 1 EraseBytes-
#2616108	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1690/20000 MS: 1 EraseBytes-
#2616110	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3285/20000 MS: 2 CopyPart-EraseBytes-
#2616181	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8503/20000 MS: 1 EraseBytes-
#2616448	REDUCE cov: 12643 ft: 75066 corp: 5936/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1418/20000 MS: 2 CMP-EraseBytes- DE: "\377\377\377\377"-
#2616470	NEW    cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 19939/20000 MS: 2 CopyPart-CopyPart-
#2616516	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10743/20000 MS: 1 EraseBytes-
#2616679	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 843/20000 MS: 3 ShuffleBytes-InsertByte-EraseBytes-
#2616713	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5750/20000 MS: 4 CrossOver-ChangeBinInt-ChangeBit-EraseBytes-
#2616836	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1449/20000 MS: 3 ShuffleBytes-ChangeBit-EraseBytes-
#2616887	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 21/20000 MS: 1 EraseBytes-
#2616948	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9286/20000 MS: 1 EraseBytes-
#2617184	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2307/20000 MS: 1 EraseBytes-
#2617571	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9112/20000 MS: 2 CrossOver-EraseBytes-
#2617862	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2622/20000 MS: 1 EraseBytes-
#2618033	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4669/20000 MS: 1 EraseBytes-
#2618278	REDUCE cov: 12643 ft: 75067 corp: 5937/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1004/20000 MS: 5 ChangeBinInt-CopyPart-PersAutoDict-ChangeBinInt-EraseBytes- DE: "NoOp"-
#2618279	NEW    cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10811/20000 MS: 1 CopyPart-
#2618525	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2312/20000 MS: 1 EraseBytes-
#2618566	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 11601/20000 MS: 1 EraseBytes-
#2618793	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8047/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2618814	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6040/20000 MS: 1 EraseBytes-
#2618840	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 60/20000 MS: 1 EraseBytes-
#2618941	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10659/20000 MS: 1 EraseBytes-
#2618983	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8498/20000 MS: 2 InsertByte-EraseBytes-
#2619175	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7602/20000 MS: 2 ShuffleBytes-EraseBytes-
#2619226	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1926/20000 MS: 1 EraseBytes-
#2619316	REDUCE cov: 12643 ft: 75069 corp: 5938/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3703/20000 MS: 5 ChangeASCIIInt-PersAutoDict-ShuffleBytes-ChangeByte-EraseBytes- DE: "\001\000\000\001"-
#2619413	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 14209/20000 MS: 2 PersAutoDict-ChangeByte- DE: "\000\000\002l"-
#2619444	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2796/20000 MS: 1 EraseBytes-
#2619550	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 19512/20000 MS: 1 EraseBytes-
#2619612	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6833/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2619919	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 14875/20000 MS: 2 PersAutoDict-EraseBytes- DE: "\030\000\000\000"-
#2619948	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3045/20000 MS: 4 ChangeASCIIInt-PersAutoDict-CopyPart-EraseBytes- DE: "\000\000\000\000\000\000\000\010"-
#2620004	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8104/20000 MS: 1 EraseBytes-
#2620096	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 965/20000 MS: 2 ChangeByte-EraseBytes-
#2620182	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12424/20000 MS: 1 CrossOver-
#2620236	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 380/20000 MS: 4 PersAutoDict-InsertByte-ChangeBinInt-EraseBytes- DE: "\001\000\000\000\000\000\000\014"-
#2620383	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 302/20000 MS: 2 CrossOver-EraseBytes-
#2620602	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8505/20000 MS: 4 ChangeBit-ChangeBit-PersAutoDict-EraseBytes- DE: "size"-
#2620723	REDUCE cov: 12646 ft: 75072 corp: 5939/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 16220/20000 MS: 1 EraseBytes-
#2620805	REDUCE cov: 12646 ft: 75078 corp: 5940/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 15231/20000 MS: 2 CopyPart-InsertByte-
#2621226	REDUCE cov: 12646 ft: 75078 corp: 5940/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3551/20000 MS: 1 EraseBytes-
#2621265	REDUCE cov: 12646 ft: 75078 corp: 5940/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2635/20000 MS: 4 ShuffleBytes-ChangeByte-PersAutoDict-EraseBytes- DE: "TrailingZeroCountI"-
#2621399	REDUCE cov: 12646 ft: 75078 corp: 5940/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 223/20000 MS: 4 PersAutoDict-ShuffleBytes-CrossOver-EraseBytes- DE: "\003\000"-
#2621887	REDUCE cov: 12646 ft: 75078 corp: 5940/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1425/20000 MS: 3 PersAutoDict-PersAutoDict-EraseBytes- DE: "\000\000\000e"-"TypeArgumentsInference19"-
#2622093	REDUCE cov: 12646 ft: 75078 corp: 5940/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1855/20000 MS: 1 EraseBytes-
#2622241	REDUCE cov: 12650 ft: 75082 corp: 5941/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3503/20000 MS: 3 InsertByte-PersAutoDict-CrossOver- DE: "Zip4"-
#2622279	REDUCE cov: 12650 ft: 75082 corp: 5941/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1438/20000 MS: 3 CMP-CMP-EraseBytes- DE: "p\000\000\000"-"\000\000\000\002"-
#2622547	REDUCE cov: 12650 ft: 75082 corp: 5941/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1082/20000 MS: 3 PersAutoDict-ChangeByte-EraseBytes- DE: "\034\000\000\000\000\000\000\000"-
#2622899	REDUCE cov: 12650 ft: 75082 corp: 5941/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4058/20000 MS: 2 InsertByte-EraseBytes-
#2622990	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 271/20000 MS: 1 EraseBytes-
#2623266	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4317/20000 MS: 1 EraseBytes-
#2623675	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 17653/20000 MS: 4 EraseBytes-InsertByte-CopyPart-ChangeBit-
#2623721	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1497/20000 MS: 1 EraseBytes-
#2623989	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6152/20000 MS: 3 ChangeBinInt-InsertByte-EraseBytes-
#2624177	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12303/20000 MS: 3 PersAutoDict-InsertByte-EraseBytes- DE: "{\000\000\000"-
#2624196	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 13572/20000 MS: 4 CopyPart-ChangeASCIIInt-ShuffleBytes-EraseBytes-
#2624252	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1410/20000 MS: 1 EraseBytes-
#2624353	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 374/20000 MS: 1 EraseBytes-
#2624499	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8496/20000 MS: 1 EraseBytes-
#2624525	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2400/20000 MS: 1 EraseBytes-
#2624626	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12926/20000 MS: 1 EraseBytes-
#2624807	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 768/20000 MS: 1 EraseBytes-
#2625005	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 15214/20000 MS: 3 InsertRepeatedBytes-ChangeByte-EraseBytes-
#2625070	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3809/20000 MS: 5 ChangeASCIIInt-PersAutoDict-CopyPart-CopyPart-EraseBytes- DE: "N\004\000\000"-
#2625139	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 689/20000 MS: 4 CopyPart-InsertByte-ChangeASCIIInt-EraseBytes-
#2625306	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 334/20000 MS: 2 CMP-EraseBytes- DE: "Core"-
#2625387	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1678/20000 MS: 1 EraseBytes-
#2625504	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2256/20000 MS: 2 ChangeBit-EraseBytes-
#2625565	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3667/20000 MS: 1 EraseBytes-
#2625596	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 65/20000 MS: 1 EraseBytes-
#2625607	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12401/20000 MS: 1 EraseBytes-
#2626406	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3999/20000 MS: 4 InsertRepeatedBytes-ChangeBit-EraseBytes-EraseBytes-
#2626433	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2341/20000 MS: 2 PersAutoDict-EraseBytes- DE: "ants"-
#2626524	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8338/20000 MS: 1 EraseBytes-
#2626715	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7765/20000 MS: 1 EraseBytes-
#2626808	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 13272/20000 MS: 3 InsertRepeatedBytes-ChangeByte-EraseBytes-
#2626844	REDUCE cov: 12651 ft: 75083 corp: 5942/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5346/20000 MS: 1 EraseBytes-
#2627024	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 17318/20000 MS: 5 CopyPart-ChangeASCIIInt-ShuffleBytes-ShuffleBytes-CopyPart-
#2627060	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 58/20000 MS: 1 EraseBytes-
#2627072	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2858/20000 MS: 2 ShuffleBytes-EraseBytes-
#2627188	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3878/20000 MS: 1 EraseBytes-
#2627291	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12910/20000 MS: 3 ChangeByte-ChangeBit-EraseBytes-
#2627492	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2096/20000 MS: 1 EraseBytes-
#2627786	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9/20000 MS: 4 ChangeBit-CopyPart-InsertByte-EraseBytes-
#2627858	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7086/20000 MS: 2 CrossOver-EraseBytes-
#2627880	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 769/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2628092	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 11350/20000 MS: 2 CrossOver-EraseBytes-
#2628096	REDUCE cov: 12651 ft: 75084 corp: 5943/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4288/20000 MS: 4 ChangeASCIIInt-ChangeBinInt-ChangeASCIIInt-EraseBytes-
	NEW_FUNC[1/1]: 0x5641c4597611
#2628276	REDUCE cov: 12655 ft: 75088 corp: 5944/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2642/20000 MS: 5 ChangeASCIIInt-ChangeBit-CopyPart-ChangeByte-ChangeByte-
#2628678	REDUCE cov: 12655 ft: 75088 corp: 5944/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1348/20000 MS: 2 ChangeBinInt-EraseBytes-
#2628812	REDUCE cov: 12655 ft: 75089 corp: 5945/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 15984/20000 MS: 4 ChangeBit-CrossOver-CMP-CopyPart- DE: "\000\000\000\000\000\000\000\001"-
#2628858	NEW    cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 19380/20000 MS: 1 CopyPart-
#2628966	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 134/20000 MS: 3 CopyPart-ShuffleBytes-EraseBytes-
#2629039	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9675/20000 MS: 3 PersAutoDict-CopyPart-CrossOver- DE: "Paul"-
#2629040	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7057/20000 MS: 1 EraseBytes-
#2629212	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6966/20000 MS: 2 PersAutoDict-EraseBytes- DE: "W\000\000\000"-
#2629238	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 281/20000 MS: 1 EraseBytes-
#2629273	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8096/20000 MS: 5 InsertByte-ChangeBit-PersAutoDict-ChangeBinInt-EraseBytes- DE: "IntT"-
#2629560	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1346/20000 MS: 2 CMP-EraseBytes- DE: "\002\000\000\000\000\000\000\000"-
#2630037	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3346/20000 MS: 2 InsertByte-EraseBytes-
#2630291	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 853/20000 MS: 4 CMP-ShuffleBytes-ChangeBinInt-EraseBytes- DE: "fail"-
#2630795	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 14540/20000 MS: 4 ChangeBit-CrossOver-ShuffleBytes-EraseBytes-
#2630946	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5258/20000 MS: 1 EraseBytes-
#2631215	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9185/20000 MS: 4 ChangeASCIIInt-InsertByte-ChangeASCIIInt-EraseBytes-
#2631488	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 11178/20000 MS: 3 CopyPart-CMP-CrossOver- DE: "Cos"-
#2631637	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 213/20000 MS: 4 InsertByte-CrossOver-ChangeBit-EraseBytes-
#2631693	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2350/20000 MS: 1 EraseBytes-
#2631724	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 16/20000 MS: 1 EraseBytes-
#2631761	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6519/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2631837	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 222/20000 MS: 1 EraseBytes-
#2631861	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1950/20000 MS: 4 ChangeBit-ChangeASCIIInt-ChangeBit-EraseBytes-
#2632052	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 66/20000 MS: 1 EraseBytes-
#2632068	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2875/20000 MS: 1 EraseBytes-
#2632135	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1527/20000 MS: 2 ChangeBit-EraseBytes-
#2632241	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 17642/20000 MS: 1 EraseBytes-
#2632312	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 601/20000 MS: 1 EraseBytes-
#2632427	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7348/20000 MS: 5 CopyPart-ChangeBinInt-InsertByte-ChangeASCIIInt-EraseBytes-
#2632537	REDUCE cov: 12655 ft: 75090 corp: 5946/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4390/20000 MS: 5 ChangeASCIIInt-InsertByte-InsertByte-ChangeBinInt-EraseBytes-
#2633053	NEW    cov: 12655 ft: 75092 corp: 5947/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5094/20000 MS: 1 CopyPart-
#2633245	REDUCE cov: 12655 ft: 75092 corp: 5947/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 86/20000 MS: 2 InsertByte-EraseBytes-
#2633258	REDUCE cov: 12655 ft: 75092 corp: 5947/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6562/20000 MS: 3 InsertByte-ShuffleBytes-EraseBytes-
#2633314	REDUCE cov: 12655 ft: 75092 corp: 5947/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2135/20000 MS: 1 EraseBytes-
#2633610	REDUCE cov: 12655 ft: 75092 corp: 5947/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 15636/20000 MS: 1 EraseBytes-
#2633744	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9869/20000 MS: 4 ChangeByte-PersAutoDict-CMP-CopyPart- DE: "n\000\000\000"-"fail"-
#2633790	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9042/20000 MS: 1 EraseBytes-
#2633853	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10157/20000 MS: 3 PersAutoDict-ChangeByte-CrossOver- DE: "{\000\000\000"-
#2633896	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 838/20000 MS: 3 ChangeBit-ChangeBit-EraseBytes-
#2633927	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1397/20000 MS: 1 EraseBytes-
#2633989	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1834/20000 MS: 2 InsertByte-EraseBytes-
#2633999	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3749/20000 MS: 5 CopyPart-ChangeASCIIInt-ChangeBinInt-ChangeASCIIInt-EraseBytes-
#2634000	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3724/20000 MS: 1 EraseBytes-
#2634072	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 19402/20000 MS: 2 ShuffleBytes-EraseBytes-
#2634324	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5230/20000 MS: 2 ShuffleBytes-EraseBytes-
#2634822	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 13603/20000 MS: 3 ChangeByte-ChangeASCIIInt-EraseBytes-
#2634831	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 443/20000 MS: 4 ChangeASCIIInt-ChangeByte-CopyPart-EraseBytes-
#2634903	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12476/20000 MS: 2 ChangeBit-EraseBytes-
#2635140	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 574/20000 MS: 2 PersAutoDict-EraseBytes- DE: "#\002\000\000"-
#2635518	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6005/20000 MS: 3 InsertByte-ChangeBit-EraseBytes-
#2635699	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2426/20000 MS: 1 EraseBytes-
#2636141	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 18033/20000 MS: 2 CrossOver-EraseBytes-
#2636147	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3532/20000 MS: 1 EraseBytes-
#2636162	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1809/20000 MS: 5 CopyPart-ChangeBinInt-ChangeByte-ChangeByte-EraseBytes-
#2636183	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2586/20000 MS: 1 EraseBytes-
#2636209	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 339/20000 MS: 1 EraseBytes-
#2636403	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1725/20000 MS: 4 CrossOver-CMP-ChangeASCIIInt-EraseBytes- DE: "PauliY"-
#2636435	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3064/20000 MS: 2 InsertRepeatedBytes-EraseBytes-
#2636499	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4381/20000 MS: 4 InsertByte-PersAutoDict-CMP-EraseBytes- DE: "\000\000\000\000\000\000\000\026"-">\000\000\000"-
#2636567	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 937/20000 MS: 3 ChangeBit-ChangeBit-EraseBytes-
#2636665	REDUCE cov: 12655 ft: 75099 corp: 5948/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5094/20000 MS: 3 ChangeBinInt-InsertRepeatedBytes-EraseBytes-
#2636688	REDUCE cov: 12655 ft: 75101 corp: 5949/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8041/20000 MS: 3 InsertRepeatedBytes-ChangeASCIIInt-CrossOver-
#2636799	REDUCE cov: 12655 ft: 75101 corp: 5949/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9/20000 MS: 1 EraseBytes-
#2636801	NEW    cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 657/20000 MS: 2 InsertByte-EraseBytes-
#2636818	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6062/20000 MS: 2 CrossOver-EraseBytes-
#2636819	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 14666/20000 MS: 1 EraseBytes-
#2636919	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9278/20000 MS: 5 ChangeBit-ShuffleBytes-ShuffleBytes-ChangeByte-EraseBytes-
#2636977	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1693/20000 MS: 3 PersAutoDict-ChangeBit-EraseBytes- DE: "qs"-
#2637018	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 433/20000 MS: 1 EraseBytes-
#2637176	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 677/20000 MS: 3 ChangeASCIIInt-InsertByte-EraseBytes-
#2637203	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1430/20000 MS: 2 PersAutoDict-EraseBytes- DE: "AlwaysFail"-
#2637204	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 227/20000 MS: 1 EraseBytes-
#2637236	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2332/20000 MS: 2 CopyPart-EraseBytes-
#2637759	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 47/20000 MS: 3 InsertByte-ChangeBit-EraseBytes-
#2637766	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1168/20000 MS: 2 CopyPart-EraseBytes-
#2637859	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2979/20000 MS: 3 ChangeBinInt-PersAutoDict-EraseBytes- DE: "DrawRandom"-
#2637935	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1829/20000 MS: 1 EraseBytes-
#2638223	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1797/20000 MS: 3 CopyPart-ChangeBit-EraseBytes-
#2638476	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8697/20000 MS: 3 ChangeBit-InsertRepeatedBytes-EraseBytes-
#2638688	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 897/20000 MS: 2 InsertByte-EraseBytes-
#2638709	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 11083/20000 MS: 1 EraseBytes-
#2638955	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1480/20000 MS: 1 EraseBytes-
#2639077	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9815/20000 MS: 2 InsertByte-EraseBytes-
#2639079	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10834/20000 MS: 2 PersAutoDict-EraseBytes- DE: "\032\001\000\000"-
#2639329	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5138/20000 MS: 5 EraseBytes-ChangeBinInt-EraseBytes-ChangeByte-CopyPart-
#2639395	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7460/20000 MS: 1 EraseBytes-
#2639477	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3402/20000 MS: 2 CrossOver-EraseBytes-
#2639484	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10913/20000 MS: 2 CMP-EraseBytes- DE: "\010\000\000\000\000\000\000\000"-
#2639547	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 455/20000 MS: 3 ChangeASCIIInt-InsertByte-EraseBytes-
#2639793	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6357/20000 MS: 1 EraseBytes-
#2639950	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 18652/20000 MS: 2 CrossOver-EraseBytes-
#2640536	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 636/20000 MS: 1 EraseBytes-
#2640635	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 35/20000 MS: 4 ShuffleBytes-PersAutoDict-ChangeBit-EraseBytes- DE: "\001\000\000\000"-
#2640673	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3865/20000 MS: 3 ChangeByte-ChangeASCIIInt-EraseBytes-
#2640925	REDUCE cov: 12655 ft: 75103 corp: 5950/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2661/20000 MS: 2 ChangeByte-EraseBytes-
#2640937	NEW    cov: 12655 ft: 75104 corp: 5951/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 12224/20000 MS: 2 ChangeByte-EraseBytes-
#2641124	REDUCE cov: 12655 ft: 75104 corp: 5951/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 75/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2641276	REDUCE cov: 12655 ft: 75104 corp: 5951/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 235/20000 MS: 2 PersAutoDict-EraseBytes- DE: "VariableDeclaration9"-
#2641404	REDUCE cov: 12655 ft: 75104 corp: 5951/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3549/20000 MS: 3 ChangeASCIIInt-ChangeByte-EraseBytes-
#2642050	REDUCE cov: 12655 ft: 75104 corp: 5951/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 91/20000 MS: 1 EraseBytes-
#2642087	REDUCE cov: 12655 ft: 75104 corp: 5951/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3123/20000 MS: 2 EraseBytes-CopyPart-
#2642288	REDUCE cov: 12655 ft: 75104 corp: 5951/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2775/20000 MS: 1 EraseBytes-
#2642590	NEW    cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 9741/20000 MS: 2 ChangeASCIIInt-CopyPart-
#2642674	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 6867/20000 MS: 4 ChangeBit-InsertByte-CopyPart-CrossOver-
#2642781	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1519/20000 MS: 2 ChangeBinInt-EraseBytes-
#2643042	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1308/20000 MS: 1 EraseBytes-
#2643060	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 41/20000 MS: 3 InsertRepeatedBytes-InsertByte-EraseBytes-
#2643091	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 8178/20000 MS: 1 EraseBytes-
#2643234	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 13482/20000 MS: 3 ChangeBit-CopyPart-EraseBytes-
#2643310	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4718/20000 MS: 1 EraseBytes-
#2643323	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3278/20000 MS: 3 CrossOver-InsertByte-EraseBytes-
#2643444	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2226/20000 MS: 1 EraseBytes-
#2643550	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2302/20000 MS: 1 EraseBytes-
#2643617	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 2227/20000 MS: 2 ChangeByte-EraseBytes-
#2643623	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1883/20000 MS: 1 EraseBytes-
#2643658	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 7621/20000 MS: 5 InsertByte-InsertByte-ShuffleBytes-CopyPart-EraseBytes-
#2643674	REDUCE cov: 12655 ft: 75106 corp: 5952/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3737/20000 MS: 1 EraseBytes-
#2643706	NEW    cov: 12655 ft: 75108 corp: 5953/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 19717/20000 MS: 2 ChangeASCIIInt-CopyPart-
#2643849	REDUCE cov: 12655 ft: 75108 corp: 5953/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 675/20000 MS: 3 ChangeByte-ChangeByte-EraseBytes-
#2644201	REDUCE cov: 12655 ft: 75108 corp: 5953/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 538/20000 MS: 2 ChangeASCIIInt-EraseBytes-
#2644321	REDUCE cov: 12655 ft: 75108 corp: 5953/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 5903/20000 MS: 5 ChangeASCIIInt-PersAutoDict-ChangeASCIIInt-ShuffleBytes-EraseBytes- DE: "\010\036"-
#2644469	REDUCE cov: 12655 ft: 75108 corp: 5953/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4193/20000 MS: 3 ShuffleBytes-ChangeBinInt-EraseBytes-
#2644477	NEW    cov: 12655 ft: 75110 corp: 5954/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 17556/20000 MS: 3 ChangeByte-InsertRepeatedBytes-CrossOver-
#2644503	REDUCE cov: 12655 ft: 75110 corp: 5954/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10364/20000 MS: 1 EraseBytes-
#2644901	REDUCE cov: 12655 ft: 75110 corp: 5954/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 877/20000 MS: 3 ChangeBit-InsertByte-EraseBytes-
#2645014	REDUCE cov: 12655 ft: 75110 corp: 5954/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 1736/20000 MS: 3 InsertByte-CrossOver-EraseBytes-
#2645059	REDUCE cov: 12655 ft: 75110 corp: 5954/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 10107/20000 MS: 5 PersAutoDict-ChangeBit-PersAutoDict-ShuffleBytes-EraseBytes- DE: "\377\377\377\377\377\377\377\007"-"\001\000\000\000\000\000\000\013"-
#2645080	REDUCE cov: 12655 ft: 75110 corp: 5954/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 3504/20000 MS: 1 EraseBytes-
#2645201	REDUCE cov: 12655 ft: 75110 corp: 5954/36Mb lim: 20000 exec/s: 562 rss: 178Mb L: 4802/20000 MS: 1 EraseBytes-
==5070== ERROR: libFuzzer: out-of-memory (used: 4204Mb; limit: 4096Mb)
   To change the out-of-memory limit use -rss_limit_mb=<N>

MS: 1 CopyPart-; base unit: 2352a840b4f8b0f0c6399a858ba64bc13065d493
artifact_prefix='/home/runner/work/qsharp/qsharp/fuzz/artifacts/qsharp/'; Test unit written to /home/runner/work/qsharp/qsharp/fuzz/artifacts/qsharp/oom-f894ca84fa5b476a2b9207fa02182ee3cd0778e7
SUMMARY: libFuzzer: out-of-memory

────────────────────────────────────────────────────────────────────────────────

Failing input:

	fuzz/artifacts/qsharp/oom-f894ca84fa5b476a2b9207fa02182ee3cd0778e7

Output of `std::fmt::Debug`:

	[110, 97, 109, 101, 115, 112, 97, 99, 101, 32, 84, 101, 115, 116, 49, 54, 32, 123, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 76, 97, 109, 98, 100, 97, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 120, 49, 32, 61, 32, 40, 120, 49, 32, 45, 62, 32, 36, 34, 123, 120, 49, 125, 34, 41, 40, 49, 46, 48, 41, 59, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 113, 49, 32, 61, 32, 81, 117, 98, 105, 116, 91, 40, 120, 32, 45, 62, 32, 120, 32, 43, 32, 49, 41, 40, 49, 41, 93, 59, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 113, 50, 32, 61, 32, 40, 81, 117, 98, 105, 116, 91, 40, 120, 32, 45, 62, 32, 120, 32, 43, 32, 49, 41, 40, 49, 41, 93, 44, 32, 81, 117, 98, 105, 116, 40, 41, 44, 32, 81, 117, 98, 105, 116, 91, 40, 120, 32, 45, 62, 32, 120, 32, 61, 61, 32, 49, 46, 48, 32, 63, 32, 48, 32, 124, 32, 49, 41, 40, 49, 46, 48, 41, 93, 41, 59, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 102, 49, 32, 61, 32, 40, 102, 111, 111, 41, 32, 45, 62, 32, 102, 111, 111, 32, 43, 32, 49, 32, 43, 32, 102, 111, 111, 59, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 102, 50, 32, 61, 32, 40, 102, 111, 111, 44, 32, 98, 97, 114, 41, 32, 45, 62, 32, 102, 111, 111, 32, 43, 32, 98, 97, 114, 32, 43, 32, 32, 102, 51, 32, 61, 32, 102, 111, 111, 32, 45, 62, 32, 102, 111, 111, 123, 125, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 120, 32, 45, 62, 32, 120, 32, 111, 114, 32, 116, 114, 117, 101, 41, 40, 116, 114, 117, 101, 41, 32, 123, 10, 32, 32, 32, 32, 32, 123, 125, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 120, 32, 45, 62, 32, 120, 32, 111, 114, 32, 116, 114, 117, 101, 41, 40, 116, 114, 117, 101, 41, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 32, 101, 108, 105, 102, 32, 40, 121, 32, 45, 62, 32, 121, 32, 111, 114, 32, 121, 32, 111, 114, 32, 116, 114, 117, 101, 41, 40, 116, 114, 117, 101, 41, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 32, 101, 108, 105, 102, 32, 40, 121, 32, 45, 62, 32, 121, 32, 61, 61, 32, 49, 41, 40, 49, 41, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 108, 105, 102, 32, 76, 101, 110, 103, 116, 104, 40, 99, 116, 108, 115, 41, 32, 60, 61, 32, 10, 32, 32, 32, 32, 32, 111, 111, 44, 32, 102, 111, 111, 41, 32, 45, 62, 32, 102, 111, 111, 32, 43, 32, 102, 111, 111, 59, 10, 32, 32, 32, 32, 125, 10, 125, 10]

Reproduce with:

	cargo fuzz run -O --features=do_fuzz --sanitizer=none qsharp fuzz/artifacts/qsharp/oom-f894ca84fa5b476a2b9207fa02182ee3cd0778e7

Minimize test case with:

	cargo fuzz tmin -O --features=do_fuzz --sanitizer=none qsharp fuzz/artifacts/qsharp/oom-f894ca84fa5b476a2b9207fa02182ee3cd0778e7

────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit status: 71

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: cargo_fuzz::project::FuzzProject::exec_fuzz
   2: cargo_fuzz::main
   3: std::sys::backtrace::__rust_begin_short_backtrace
   4: std::rt::lang_start::{{closure}}
   5: std::rt::lang_start_internal
   6: main
   7: <unknown>
   8: __libc_start_main
   9: _start
```

</details>

<details><summary><b>The branch/commit the bug has been found in:</b> Click.</summary>
If the developers fail to repro the bug in the latest <code>main</code> then the branch/commit info below can help them to make sure
that they are using the correct way to repro. If the bug is reproducible in the branch/commit below, but not in latest <code>main</code>,
then the bug is likely fixed already or is not in the <code>main</code> branch.

```log
Branch: * main

commit fbc415fb9c2729b45f64743add54029f745ede71
Author: Scott Carda <55811729+ScottCarda-MS@users.noreply.github.com>
Date:   Fri May 16 14:20:16 2025 -0700

    Drop `ms.topic` Metadata Field for all Non-Index Doc Files (#2422)
    
    As requested by the doc team, they now have a script that will add the
    `ms.topic` field with a value that they determine, so we shouldn't
    generate `ms.topic` fields.
```

</details>

**Other Info**

- [**Workflow**](https://github.com/microsoft/qsharp/actions/runs/15095461692) (contains the run artifacts).
- **Workflow Agent System Info:** `ubuntu-latest: Linux fv-az1910-449 6.11.0-1014-azure #14~24.04.1-Ubuntu SMP Thu Apr 24 17:41:03 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`.
- **Bug Reporting Timestamp:** 2025.05.18 12:54 UTC (UTC - 8:00 = PST. UTC - 7:00 = PDT).

### PR DESCRIPTION
**Pull request by swernli**
This change updats the check we have in type inference to ensure an inference type is not bound to another type that includes itself. The previous check worked for simple cases where the target type directly contained the inference type, but fails to catch recursion where the target type contained inference types that indicrectly pointed to the original inference type through the current type inference solution. With this check in place, we can now explicitly give an error when a recursive type is detected.
Fixes #2426

### CODE REVIEW

File: compiler/qsc/src/interpret/tests.rs [hunk 1]
```diff
@@ -2230,5 +2230,43 @@ mod given_interpreter {
                 "#]],
             );
         }
+
+        #[test]
+        fn fuzz_2426() {
```
Comment (minestarks) [inline compiler/qsc/src/interpret/tests.rs:2235]: There's got to be a better name. `recursive_type_constraint` maybe?

File: compiler/qsc/src/interpret/tests.rs [hunk 2]
```diff
@@ -2230,5 +2230,43 @@ mod given_interpreter {
...
+                crate::compile::package_store_with_stdlib(TargetCapabilityFlags::all());
+            match Interpreter::new(
+                sources,
+                PackageType::Lib,
+                TargetCapabilityFlags::all(),
+                LanguageFeatures::default(),
+                store,
+                &[(std_id, None)],
+            ) {
+                Ok(_) => panic!("interpreter should fail with error"),
```
Comment (minestarks) [inline compiler/qsc/src/interpret/tests.rs:2253]: `.expect_err`?

File: compiler/qsc/src/interpret/tests.rs (hunk 1 above)
Comment (swernli) [reply compiler/qsc/src/interpret/tests.rs:2235]: I was following the naming convention we've used for the OpenQASM fuzz tests (see compiler/qsc_qasm/src/tests/fuzz.rs), but as those are in a fuzzing-specific file it makes more sense there. I personally like knowing right way when looking at the test that it was found via fuzzing and what the corresponding issue number is, but that can be accomplished with just a comment, so I'll adjust this test name to better fit the pattern in this file.

**Review by idavis — APPROVED** [review]
