### PR TITLE
Controlled rotation gates don't check that target and controls are distinct qubits

### LINKED ISSUE #1339: Controlled rotation gates don't check that target and controls are distinct qubits
**Describe the bug**

It is possible to apply Controlled Ry and Rz gates with 2 controls and target that is the same as one of the controls, and have no exception happen.

**To Reproduce**

The smallest repro I could find was:

```qsharp
operation BugDemo() : Unit {
    use qs = Qubit[2];
    ApplyToEach(H, qs);
    Controlled Ry(qs, (0.5, qs[1]));
    ResetAll(qs);
}

BugDemo()
```

Using only one control doesn't trigger the bug (the exception is thrown correctly), and using X instead of Ry also doesn't trigger it.

**Expected behavior**

Controlled gates are not defined for targets that are the same as controls, so I expect an exception for any combination of gates and control/targets that have overlapping controls and targets. (This was the case in Classic QDK too.)

**System information**

- qsharp 1.3.1

### PR DESCRIPTION
**Pull request by swernli**
Fixes #1339

### CODE REVIEW

File: compiler/qsc_eval/src/val.rs [hunk 1]
```diff
@@ -381,6 +381,31 @@ impl Value {
             Value::Var(_) => "Var",
         }
     }
+
+    #[must_use]
+    pub fn to_qubits(&self) -> Vec<Qubit> {
```
Comment (minestarks) [inline compiler/qsc_eval/src/val.rs:386]: The name of this made me think it's some kind of conversion operator, which confused me. It's more of a getter. `qubits()` would be a better name IMO (as in `get_qubits`, but Rust doesn't like prefixes in getter names)

**Review by minestarks — APPROVED** [review]

File: compiler/qsc_eval/src/val.rs (hunk 1 above)
Comment (swernli) [reply compiler/qsc_eval/src/val.rs:386]: Updated the name and added a comment to help explain the usage.

File: compiler/qsc_partial_eval/src/lib.rs [hunk 2]
```diff
@@ -1181,12 +1182,16 @@ impl<'a> PartialEvaluator<'a> {
...
-        );
+        let (args, ctls_arg) = self
+            .resolve_args(
+                (store_item_id.package, callable_decl.input).into(),
+                args_value.clone(),
+                ctls,
+                fixed_args,
+            )
+            .map_err(|()| {
+                Error::EvaluationFailed("qubis in invocation are not unique".to_string(), args_span)
```
Comment (idavis) [inline compiler/qsc_partial_eval/src/lib.rs:1193]: Qubits

File: compiler/qsc_partial_eval/src/lib.rs [hunk 3]
```diff
@@ -1181,12 +1182,16 @@ impl<'a> PartialEvaluator<'a> {
...
-            fixed_args,
-        );
+        let (args, ctls_arg) = self
+            .resolve_args(
+                (store_item_id.package, callable_decl.input).into(),
+                args_value.clone(),
+                ctls,
+                fixed_args,
+            )
+            .map_err(|()| {
```
Comment (idavis) [inline compiler/qsc_partial_eval/src/lib.rs:1192]: Feels odd that we are returning an error of `()` rather than creating a real error kind, then having to map the empty error here

Comment (swernli) [reply compiler/qsc_partial_eval/src/lib.rs:1192]: The alternative is to pass `args_span` through to the underlying `resolve_args` function. I'll try that version to see if the ergonomics are better.

File: compiler/qsc_partial_eval/src/lib.rs (hunk 2 above)
Comment (swernli) [reply compiler/qsc_partial_eval/src/lib.rs:1193]: Fixed by relying on the same string from evaluator.
