### PR TITLE
Return error instead of panic if an item ambiguously references a prelude or local scope

### LINKED ISSUE #411: Fuzz: "ambiguity in prelude resolution" (ubuntu-latest)
The fuzz-testing workflow has detected a bug.

<details><summary><b>Auto-Minimized Fuzzing Input That Triggers the Bug:</b> Click this line.</summary>
<b>Note:</b> If the input is multi-line then the end-of-line characters '\n' (0x0A) and '\r' (0x0D)
may affect the reproducibility of the bug. If you fail to repro the bug with the input shown below
then you may want to go to the <a href=https://github.com/microsoft/qsharp/actions/runs/5303381055>workflow</a> that reported this GitHub bug,
download the artifact, and extract the file with the exact minimized input.

```qs

namespace Microsoft.Quantum.Canon{function Length () :n{ }}
namespace Mc{operation i() :t{Length
```

</details>

<details><summary><b>Fuzzing <code>stderr</code> Log</b> (last 62kB), includes the stack trace: Click.</summary>
The fragment of interest starts with "panicked at".

```gdb
5bb10017e0ce4e7abe50/library/core/src/slice/iter/macros.rs:237:21
   9: qsc_ast::visit::walk_block
             at ./compiler/qsc_ast/src/visit.rs:172:5
  10: <qsc_frontend::resolve::With as qsc_ast::visit::Visitor>::visit_block::{{closure}}
             at ./compiler/qsc_frontend/src/resolve.rs:332:13
  11: qsc_frontend::resolve::With::with_scope
             at ./compiler/qsc_frontend/src/resolve.rs:245:9
  12: <qsc_frontend::resolve::With as qsc_ast::visit::Visitor>::visit_block
             at ./compiler/qsc_frontend/src/resolve.rs:325:9
  13: <qsc_frontend::resolve::With as qsc_ast::visit::Visitor>::visit_expr::{{closure}}
             at ./compiler/qsc_frontend/src/resolve.rs:369:64
  14: qsc_frontend::resolve::With::with_pat::{{closure}}
             at ./compiler/qsc_frontend/src/resolve.rs:255:13
  15: qsc_frontend::resolve::With::with_scope
             at ./compiler/qsc_frontend/src/resolve.rs:245:9
  16: qsc_frontend::resolve::With::with_pat
             at ./compiler/qsc_frontend/src/resolve.rs:253:9
  17: <qsc_frontend::resolve::With as qsc_ast::visit::Visitor>::visit_spec_decl
             at ./compiler/qsc_frontend/src/resolve.rs:306:13
  18: qsc_ast::visit::walk_callable_decl::{{closure}}
             at ./compiler/qsc_ast/src/visit.rs:130:65
  19: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/core/src/slice/iter/macros.rs:237:21
  20: qsc_ast::visit::walk_callable_decl
             at ./compiler/qsc_ast/src/visit.rs:130:39
  21: <qsc_frontend::resolve::With as qsc_ast::visit::Visitor>::visit_callable_decl::{{closure}}
             at ./compiler/qsc_frontend/src/resolve.rs:300:13
  22: qsc_frontend::resolve::With::with_pat::{{closure}}
             at ./compiler/qsc_frontend/src/resolve.rs:255:13
  23: qsc_frontend::resolve::With::with_scope
             at ./compiler/qsc_frontend/src/resolve.rs:245:9
  24: qsc_frontend::resolve::With::with_pat
             at ./compiler/qsc_frontend/src/resolve.rs:253:9
  25: <qsc_frontend::resolve::With as qsc_ast::visit::Visitor>::visit_callable_decl
             at ./compiler/qsc_frontend/src/resolve.rs:299:9
  26: qsc_ast::visit::walk_item
             at ./compiler/qsc_ast/src/visit.rs:94:37
  27: qsc_ast::visit::Visitor::visit_item
             at ./compiler/qsc_ast/src/visit.rs:20:9
  28: qsc_ast::visit::walk_namespace::{{closure}}
             at ./compiler/qsc_ast/src/visit.rs:86:41
  29: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/core/src/slice/iter/macros.rs:237:21
  30: qsc_ast::visit::walk_namespace
             at ./compiler/qsc_ast/src/visit.rs:86:5
  31: <qsc_frontend::resolve::With as qsc_ast::visit::Visitor>::visit_namespace::{{closure}}
             at ./compiler/qsc_frontend/src/resolve.rs:294:13
  32: qsc_frontend::resolve::With::with_scope
             at ./compiler/qsc_frontend/src/resolve.rs:245:9
  33: <qsc_frontend::resolve::With as qsc_ast::visit::Visitor>::visit_namespace
             at ./compiler/qsc_frontend/src/resolve.rs:287:9
  34: qsc_ast::visit::walk_package::{{closure}}
             at ./compiler/qsc_ast/src/visit.rs:80:23
  35: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/core/src/slice/iter/macros.rs:237:21
  36: qsc_ast::visit::walk_package
             at ./compiler/qsc_ast/src/visit.rs:77:5
  37: qsc_ast::visit::Visitor::visit_package
             at ./compiler/qsc_ast/src/visit.rs:12:9
  38: qsc_frontend::compile::resolve_all
             at ./compiler/qsc_frontend/src/compile.rs:399:29
  39: qsc_frontend::compile::compile
             at ./compiler/qsc_frontend/src/compile.rs:223:32
  40: qsc::compile::compile
             at ./compiler/qsc/src/compile.rs:25:20
  41: compile::compile::{{closure}}
             at ./fuzz/fuzz_targets/compile.rs:21:29
  42: std::thread::local::LocalKey<T>::try_with
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/thread/local.rs:270:16
  43: std::thread::local::LocalKey<T>::with
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/thread/local.rs:246:9
  44: compile::compile
             at ./fuzz/fuzz_targets/compile.rs:20:19
  45: rust_fuzzer_test_input
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/src/lib.rs:224:17
  46: libfuzzer_sys::test_input_wrap::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/src/lib.rs:61:9
  47: std::panicking::try::do_call
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:500:40
  48: std::panicking::try
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:464:19
  49: std::panic::catch_unwind
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panic.rs:142:14
  50: LLVMFuzzerTestOneInput
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/src/lib.rs:59:22
  51: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/libfuzzer/FuzzerLoop.cpp:612:15
  52: _ZN6fuzzer6Fuzzer6RunOneEPKhmbPNS_9InputInfoEbPb
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/libfuzzer/FuzzerLoop.cpp:514:22
  53: _ZN6fuzzer6Fuzzer16MutateAndTestOneEv
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/libfuzzer/FuzzerLoop.cpp:758:25
  54: _ZN6fuzzer6Fuzzer4LoopERSt6vectorINS_9SizedFileESaIS2_EE
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/libfuzzer/FuzzerLoop.cpp:903:21
  55: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/libfuzzer/FuzzerDriver.cpp:912:10
  56: main
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/libfuzzer/FuzzerMain.cpp:20:30
  57: <unknown>
  58: __libc_start_main
  59: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
==4332== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 2 CopyPart-CrossOver-; base unit: f8f9bb114f81b7c9a0bc1e7dbd5d1f5ba0a911f0
artifact_prefix='/home/runner/work/qsharp/qsharp/fuzz/artifacts/compile/'; Test unit written to /home/runner/work/qsharp/qsharp/fuzz/artifacts/compile/crash-4b6cb454e0349e70993837198d086942988b6d32

────────────────────────────────────────────────────────────────────────────────

Failing input:

	fuzz/artifacts/compile/crash-4b6cb454e0349e70993837198d086942988b6d32

Output of `std::fmt::Debug`:

	[47, 47, 32, 67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 40, 99, 41, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 67, 111, 114, 112, 111, 114, 97, 116, 105, 111, 110, 46, 10, 47, 47, 32, 76, 105, 99, 101, 110, 115, 101, 100, 32, 117, 110, 100, 101, 114, 32, 116, 104, 101, 32, 77, 73, 84, 32, 76, 105, 99, 101, 110, 115, 101, 46, 10, 10, 110, 97, 109, 101, 115, 112, 97, 99, 101, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 10, 123, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 32, 35, 32, 79, 118, 101, 114, 118, 105, 101, 119, 10, 32, 32, 32, 32, 47, 47, 32, 86, 97, 114, 105, 97, 110, 116, 115, 32, 111, 102, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 104, 97, 116, 32, 97, 112, 112, 108, 105, 101, 115, 32, 103, 105, 118, 101, 110, 32, 111, 110, 101, 44, 32, 116, 119, 111, 32, 97, 110, 100, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 10, 32, 32, 32, 32, 47, 47, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 111, 110, 101, 44, 32, 116, 119, 111, 32, 97, 110, 100, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 97, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 65, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 67, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 67, 65, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 32, 40, 111, 112, 32, 58, 32, 40, 81, 117, 98, 105, 116, 32, 61, 62, 32, 85, 110, 105, 116, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 61, 61, 32, 48, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 111, 110, 101, 32, 113, 117, 98, 105, 116, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 41, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 65, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 100, 106, 111, 105, 110, 116, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 114, 32, 116, 104, 101, 32, 77, 73, 84, 32, 76, 105, 99, 101, 110, 115, 101, 46, 10, 10, 110, 97, 109, 101, 115, 112, 97, 99, 101, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 10, 123, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 32, 35, 32, 79, 118, 101, 114, 118, 105, 101, 119, 10, 32, 32, 32, 32, 47, 47, 32, 86, 97, 114, 105, 97, 110, 116, 115, 32, 111, 102, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 104, 97, 116, 32, 97, 112, 112, 108, 105, 101, 115, 32, 103, 105, 118, 101, 110, 32, 111, 110, 101, 44, 32, 116, 119, 111, 32, 97, 110, 100, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 10, 32, 32, 32, 32, 47, 47, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 111, 110, 101, 44, 32, 116, 119, 111, 32, 97, 110, 100, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 97, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 65, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 67, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 67, 65, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 32, 40, 111, 112, 32, 58, 32, 40, 81, 117, 98, 105, 116, 32, 61, 62, 32, 85, 110, 105, 116, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 61, 61, 32, 48, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 111, 110, 101, 32, 113, 117, 98, 105, 116, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 41, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 65, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 100, 106, 111, 105, 110, 116, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 65, 32, 40, 111, 112, 32, 58, 32, 40, 81, 117, 98, 105, 116, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 61, 61, 32, 48, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 111, 110, 101, 32, 113, 117, 98, 105, 116, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 100, 106, 111, 105, 110, 116, 32, 105, 110, 118, 101, 114, 116, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 111, 112, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 67, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 99, 111, 110, 116, 114, 111, 108, 108, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 67, 32, 40, 111, 112, 32, 58, 32, 40, 81, 117, 98, 105, 116, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 67, 116, 108, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 61, 61, 32, 48, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 111, 110, 101, 32, 113, 117, 98, 105, 116, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 110, 116, 114, 111, 108, 108, 101, 100, 32, 100, 105, 115, 116, 114, 105, 98, 117, 116, 101, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 111, 112, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 67, 65, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 99, 111, 110, 116, 114, 111, 108, 108, 97, 98, 108, 101, 32, 97, 110, 100, 32, 97, 100, 106, 111, 105, 110, 116, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 113, 117, 98, 105, 116, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 81, 117, 98, 105, 116, 67, 65, 32, 40, 111, 112, 32, 58, 32, 40, 81, 117, 98, 105, 116, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 32, 43, 32, 67, 116, 108, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 61, 61, 32, 48, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 111, 110, 101, 32, 113, 117, 98, 105, 116, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 100, 106, 111, 105, 110, 116, 32, 105, 110, 118, 101, 114, 116, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 110, 116, 114, 111, 108, 108, 101, 100, 32, 100, 105, 115, 116, 114, 105, 98, 117, 116, 101, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 110, 116, 114, 111, 108, 108, 101, 100, 32, 97, 100, 106, 111, 105, 110, 116, 32, 100, 105, 115, 116, 114, 105, 98, 117, 116, 101, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 82, 101, 109, 97, 114, 107, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 105, 115, 32, 105, 115, 32, 101, 113, 117, 105, 118, 97, 108, 101, 110, 116, 32, 116, 111, 58, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 113, 115, 104, 97, 114, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 41, 59, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 65, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 67, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 67, 65, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 32, 40, 111, 112, 32, 58, 32, 40, 40, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 41, 32, 61, 62, 32, 85, 110, 105, 116, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 60, 32, 50, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 41, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 65, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 100, 106, 111, 105, 110, 116, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 111, 114, 112, 111, 114, 97, 116, 105, 111, 110, 46, 32, 65, 108, 108, 32, 114, 105, 103, 104, 116, 115, 32, 114, 101, 115, 101, 114, 118, 101, 100, 46, 10, 47, 47, 32, 76, 105, 99, 101, 110, 115, 101, 100, 32, 117, 110, 100, 101, 114, 32, 116, 104, 101, 32, 77, 73, 84, 32, 76, 105, 99, 101, 110, 115, 101, 46, 10, 10, 47, 47, 32, 110, 101, 101, 100, 115, 32, 116, 111, 32, 98, 101, 32, 97, 118, 97, 105, 108, 97, 98, 108, 101, 32, 102, 111, 114, 32, 116, 101, 115, 116, 105, 110, 103, 10, 110, 97, 109, 101, 115, 112, 97, 99, 101, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 111, 114, 101, 32, 123, 10, 10, 32, 32, 32, 32, 64, 65, 116, 116, 114, 105, 98, 117, 116, 101, 40, 41, 10, 32, 32, 32, 32, 110, 101, 119, 116, 121, 112, 101, 32, 65, 116, 116, 114, 105, 98, 117, 116, 101, 32, 61, 32, 85, 110, 105, 116, 59, 10, 10, 32, 32, 32, 32, 64, 65, 116, 116, 114, 105, 98, 117, 116, 101, 40, 41, 10, 32, 32, 32, 32, 110, 101, 119, 116, 121, 112, 101, 32, 69, 110, 116, 114, 121, 80, 111, 105, 110, 116, 32, 61, 32, 85, 110, 105, 116, 59, 10, 10, 32, 32, 32, 32, 64, 65, 116, 116, 114, 105, 98, 117, 116, 101, 40, 41, 10, 32, 32, 32, 32, 110, 101, 119, 116, 121, 112, 101, 32, 73, 110, 108, 105, 110, 101, 32, 61, 32, 85, 110, 105, 116, 59, 10, 10, 32, 32, 32, 32, 64, 65, 116, 116, 114, 105, 98, 117, 116, 101, 40, 41, 10, 32, 32, 32, 32, 110, 101, 119, 116, 121, 112, 101, 32, 68, 101, 112, 114, 101, 99, 97, 116, 101, 100, 32, 61, 32, 40, 78, 101, 119, 78, 97, 109, 101, 32, 58, 32, 83, 116, 114, 105, 110, 103, 41, 59, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 68, 101, 102, 97, 117, 108, 116, 60, 39, 84, 62, 32, 40, 41, 32, 58, 32, 39, 84, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 40, 110, 101, 119, 32, 39, 84, 91, 49, 93, 41, 91, 48, 93, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 76, 101, 110, 103, 116, 104, 60, 39, 84, 62, 32, 40, 97, 32, 58, 32, 39, 84, 91, 93, 41, 32, 58, 32, 73, 110, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 105, 110, 116, 114, 105, 110, 115, 105, 99, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 82, 97, 110, 103, 101, 83, 116, 97, 114, 116, 32, 40, 114, 97, 110, 103, 101, 32, 58, 32, 82, 97, 110, 103, 101, 41, 32, 58, 32, 73, 110, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 105, 110, 116, 114, 105, 110, 115, 105, 99, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 82, 97, 110, 103, 101, 69, 110, 100, 32, 40, 114, 97, 110, 103, 101, 32, 58, 32, 82, 97, 110, 103, 101, 41, 32, 58, 32, 73, 110, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 105, 110, 116, 114, 105, 110, 115, 105, 99, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 82, 97, 110, 103, 101, 83, 116, 101, 112, 32, 40, 114, 97, 110, 103, 101, 32, 58, 32, 82, 97, 110, 103, 101, 41, 32, 58, 32, 73, 110, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 105, 110, 116, 114, 105, 110, 115, 105, 99, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 82, 97, 110, 103, 101, 82, 101, 118, 101, 114, 115, 101, 40, 114, 97, 110, 103, 101, 32, 58, 32, 82, 97, 110, 103, 101, 41, 32, 58, 32, 82, 97, 110, 103, 101, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 105, 110, 116, 114, 105, 110, 115, 105, 99, 59, 10, 32, 32, 32, 32, 125, 10, 125, 10, 10, 110, 97, 109, 101, 115, 112, 97, 99, 101, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 68, 105, 97, 103, 110, 111, 115, 116, 105, 99, 115, 32, 123, 10, 10, 32, 32, 32, 32, 47, 47, 32, 110, 101, 101, 100, 115, 32, 116, 111, 32, 98, 101, 32, 97, 118, 97, 105, 108, 97, 98, 108, 101, 32, 102, 111, 114, 32, 116, 101, 115, 116, 105, 110, 103, 10, 32, 32, 32, 32, 64, 65, 116, 116, 114, 105, 98, 117, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 82, 101, 109, 97, 114, 107, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 105, 115, 32, 105, 115, 32, 101, 113, 117, 105, 118, 97, 108, 101, 110, 116, 32, 116, 111, 58, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 113, 115, 104, 97, 114, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 41, 59, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 65, 32, 40, 111, 112, 32, 58, 32, 40, 40, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 41, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 60, 32, 50, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 100, 106, 111, 105, 110, 116, 32, 105, 110, 118, 101, 114, 116, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 67, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 99, 111, 110, 116, 114, 111, 108, 108, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 82, 101, 109, 97, 114, 107, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 105, 115, 32, 105, 115, 32, 101, 113, 117, 105, 118, 97, 108, 101, 110, 116, 32, 116, 111, 58, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 113, 115, 104, 97, 114, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 41, 59, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 67, 32, 40, 111, 112, 32, 58, 32, 40, 40, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 41, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 67, 116, 108, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 60, 32, 50, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 110, 116, 114, 111, 108, 108, 101, 100, 32, 100, 105, 115, 116, 114, 105, 98, 117, 116, 101, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 67, 65, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 99, 111, 110, 116, 114, 111, 108, 108, 97, 98, 108, 101, 32, 97, 110, 100, 32, 97, 100, 106, 111, 105, 110, 116, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 119, 111, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 82, 101, 109, 97, 114, 107, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 105, 115, 32, 105, 115, 32, 101, 113, 117, 105, 118, 97, 108, 101, 110, 116, 32, 116, 111, 58, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 113, 115, 104, 97, 114, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 41, 59, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 119, 111, 81, 117, 98, 105, 116, 115, 67, 65, 32, 40, 111, 112, 32, 58, 32, 40, 40, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 41, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 32, 43, 32, 67, 116, 108, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 60, 32, 50, 41, 10, 32, 32, 32, 32, 32, 111, 100, 105, 102, 105, 101, 114, 32, 96, 65, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 100, 106, 111, 105, 110, 116, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 82, 101, 109, 97, 114, 107, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 105, 115, 32, 105, 115, 32, 101, 113, 117, 105, 118, 97, 108, 101, 110, 116, 32, 116, 111, 58, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 113, 115, 104, 97, 114, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 50, 93, 41, 59, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 104, 114, 101, 101, 81, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 104, 114, 101, 101, 81, 117, 98, 105, 116, 115, 65, 32, 40, 111, 112, 32, 58, 32, 40, 40, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 41, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 60, 32, 51, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 50, 93, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 100, 106, 111, 105, 110, 116, 32, 105, 110, 118, 101, 114, 116, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 67, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 99, 111, 110, 116, 114, 111, 108, 108, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 82, 101, 109, 97, 114, 107, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 105, 115, 32, 105, 115, 32, 101, 113, 117, 105, 118, 97, 108, 101, 110, 116, 32, 116, 111, 58, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 113, 115, 104, 97, 114, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 50, 93, 41, 59, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 104, 114, 101, 101, 81, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 104, 114, 101, 101, 81, 117, 98, 105, 116, 115, 67, 32, 40, 111, 112, 32, 58, 32, 40, 40, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 41, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 67, 116, 108, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 60, 32, 51, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 50, 93, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 110, 116, 114, 111, 108, 108, 101, 100, 32, 100, 105, 115, 116, 114, 105, 98, 117, 116, 101, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 117, 109, 109, 97, 114, 121, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 112, 112, 108, 105, 101, 115, 32, 97, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 105, 110, 32, 116, 104, 101, 32, 114, 101, 103, 105, 115, 116, 101, 114, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 101, 32, 109, 111, 100, 105, 102, 105, 101, 114, 32, 96, 67, 65, 96, 32, 105, 110, 100, 105, 99, 97, 116, 101, 115, 32, 116, 104, 97, 116, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 99, 111, 110, 116, 114, 111, 108, 108, 97, 98, 108, 101, 32, 97, 110, 100, 32, 97, 100, 106, 111, 105, 110, 116, 97, 98, 108, 101, 46, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 73, 110, 112, 117, 116, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 111, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 65, 110, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 116, 111, 32, 98, 101, 32, 97, 112, 112, 108, 105, 101, 100, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 35, 32, 114, 101, 103, 105, 115, 116, 101, 114, 10, 32, 32, 32, 32, 47, 47, 47, 32, 81, 117, 98, 105, 116, 32, 97, 114, 114, 97, 121, 32, 116, 111, 32, 116, 104, 101, 32, 102, 105, 114, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 111, 102, 32, 119, 104, 105, 99, 104, 32, 116, 104, 101, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 105, 115, 32, 97, 112, 112, 108, 105, 101, 100, 46, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 82, 101, 109, 97, 114, 107, 115, 10, 32, 32, 32, 32, 47, 47, 47, 32, 84, 104, 105, 115, 32, 105, 115, 32, 101, 113, 117, 105, 118, 97, 108, 101, 110, 116, 32, 116, 111, 58, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 113, 115, 104, 97, 114, 112, 10, 32, 32, 32, 32, 47, 47, 47, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 50, 93, 41, 59, 10, 32, 32, 32, 32, 47, 47, 47, 32, 96, 96, 96, 10, 32, 32, 32, 32, 47, 47, 47, 10, 32, 32, 32, 32, 47, 47, 47, 32, 35, 32, 83, 101, 101, 32, 65, 108, 115, 111, 10, 32, 32, 32, 32, 47, 47, 47, 32, 45, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 67, 97, 110, 111, 110, 46, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 104, 114, 101, 101, 81, 117, 98, 105, 116, 115, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 65, 112, 112, 108, 121, 84, 111, 70, 105, 114, 115, 116, 84, 104, 114, 101, 101, 81, 117, 98, 105, 116, 115, 67, 65, 32, 40, 111, 112, 32, 58, 32, 40, 40, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 44, 32, 81, 117, 98, 105, 116, 41, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 32, 43, 32, 67, 116, 108, 41, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 32, 58, 32, 81, 117, 98, 105, 116, 91, 93, 41, 32, 58, 32, 85, 110, 105, 116, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 40, 46, 46, 46, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 114, 101, 103, 105, 115, 116, 101, 114, 41, 32, 60, 32, 51, 41, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 36, 34, 77, 117, 115, 116, 32, 104, 97, 118, 101, 32, 97, 116, 32, 108, 101, 97, 115, 116, 32, 116, 104, 114, 101, 101, 32, 113, 117, 98, 105, 116, 115, 32, 116, 111, 32, 97, 99, 116, 32, 111, 110, 46, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 40, 114, 101, 103, 105, 115, 116, 101, 114, 91, 48, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 49, 93, 44, 32, 114, 101, 103, 105, 115, 116, 101, 114, 91, 50, 93, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 100, 106, 111, 105, 110, 116, 32, 105, 110, 118, 101, 114, 116, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 110, 116, 114, 111, 108, 108, 101, 100, 32, 100, 105, 115, 116, 114, 105, 98, 117, 116, 101, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 110, 116, 114, 111, 108, 108, 101, 100, 32, 97, 100, 106, 111, 105, 110, 116, 32, 100, 105, 115, 116, 114, 105, 98, 117, 116, 101, 59, 10, 32, 32, 32, 32, 125, 10, 32, 32, 32, 32, 10, 125, 10, 10, 10]

Reproduce with:

	cargo fuzz run -O --features=do_fuzz --sanitizer=none compile fuzz/artifacts/compile/crash-4b6cb454e0349e70993837198d086942988b6d32

Minimize test case with:

	cargo fuzz tmin -O --features=do_fuzz --sanitizer=none compile fuzz/artifacts/compile/crash-4b6cb454e0349e70993837198d086942988b6d32

────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit status: 77

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: cargo_fuzz::project::FuzzProject::exec_fuzz
   2: <cargo_fuzz::options::run::Run as cargo_fuzz::RunCommand>::run_command
   3: cargo_fuzz::main
   4: std::sys_common::backtrace::__rust_begin_short_backtrace
   5: std::rt::lang_start::{{closure}}
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/core/src/ops/function.rs:284:13
   7: std::panicking::try::do_call
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:500:40
   8: std::panicking::try
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:464:19
   9: std::panic::catch_unwind
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panic.rs:142:14
  10: std::rt::lang_start_internal::{{closure}}
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/rt.rs:148:48
  11: std::panicking::try::do_call
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:500:40
  12: std::panicking::try
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:464:19
  13: std::panic::catch_unwind
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panic.rs:142:14
  14: std::rt::lang_start_internal
             at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/rt.rs:148:20
  15: main
  16: <unknown>
  17: __libc_start_main
  18: _start
```

</details>

<details><summary><b>The commit in <code>main</code> the bug has been found in:</b> Click.</summary>
If the developers fail to repro the bug in the latest <code>main</code> then the commit info below can help them to make sure
that they are using the correct way to repro. If the bug is reproducible in the commit below, but not in latest <code>main</code>,
then the bug is likely fixed already.

```log
commit ff01303f0d9f97c0d8c119bce505b70e9a6b5523
Author: César Zaragoza Cortés <cesarzc@microsoft.com>
Date:   Fri Jun 16 20:28:55 2023 -0700

    Update nav for katas (rename to tutorials) (#410)
```

</details>

**Other Info**

- [**Workflow**](https://github.com/microsoft/qsharp/actions/runs/5303381055) (contains the run artifacts).
- **Workflow Agent System Info:** `ubuntu-latest: Linux fv-az174-727 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`.
- **Bug Reporting Timestamp:** 2023.06.18 11:40 UTC (UTC - 8:00 = PST. UTC - 7:00 = PDT).

### PR DESCRIPTION
**Pull request by sezna**
This PR adds a new error type, so that we gracefully report the issue instead of panicking. 

Closes #411

### CODE REVIEW

File: compiler/qsc_frontend/src/resolve.rs [hunk 1]
```diff
@@ -68,6 +68,10 @@ pub(super) enum Error {
     #[error("`{0}` not found")]
     #[diagnostic(code("Qsc.Resolve.NotFound"))]
     NotFound(String, #[label] Span),
+
+    #[error("This name shadows a global item.")]
+    #[diagnostic(code("Qsc.Resolve.ShadowsGlobal"))]
+    ShadowsGlobal(#[label] Span),
```
Comment (samarsha) [inline compiler/qsc_frontend/src/resolve.rs:74]: I agree that this should be an error instead of a panic, but this isn't the right error message. There's nothing wrong with declaring something that shadows a global. And the error doesn't occur at the declaration, it occurs at the usage. This is a different flavor of `Error::Ambiguous`, where the ambiguity is between two or more namespaces *in the prelude* rather than two or more *explicitly opened* namespaces.

**Review by samarsha — CHANGES_REQUESTED** [review]

**Comment by samarsha** [comment]
> I believe this error was just a panic previously out of convenience.

It was actually because I thought it really was impossible, but my assumptions were wrong. :) It was intended to be a panic for when we messed up the standard library. I forgot that user code can add new items to one of the prelude namespaces, creating ambiguities.

File: compiler/qsc_frontend/src/resolve.rs [hunk 2]
```diff
@@ -68,6 +68,10 @@ pub(super) enum Error {
     #[error("`{0}` not found")]
     #[diagnostic(code("Qsc.Resolve.NotFound"))]
     NotFound(String, #[label] Span),
+
+    #[error("This name results in ambiguity in a prelude namespace.")]
+    #[diagnostic(code("Qsc.Resolve.PreludeAmbiguity"))]
+    PreludeAmbiguity(#[label] Span),
```
Comment (samarsha) [inline compiler/qsc_frontend/src/resolve.rs:74]: I'd keep the naming close to the other error about ambiguous names. So maybe `Ambiguous` and `AmbiguousPrelude`?

File: compiler/qsc_frontend/src/resolve.rs [hunk 3]
```diff
@@ -68,6 +68,10 @@ pub(super) enum Error {
     #[error("`{0}` not found")]
     #[diagnostic(code("Qsc.Resolve.NotFound"))]
     NotFound(String, #[label] Span),
+
+    #[error("This name results in ambiguity in a prelude namespace.")]
```
Comment (samarsha) [inline compiler/qsc_frontend/src/resolve.rs:72]: It'd be nice to explicitly mention two of the namespaces where the name is declared, like `Ambiguous` does. It's OK that there are no spans to point to in this case (since the opens are implicit).

**Review by samarsha — CHANGES_REQUESTED** [review]

File: compiler/qsc_frontend/src/resolve.rs [hunk 4]
```diff
@@ -707,18 +738,30 @@ fn resolve_scope_locals(
...
+fn resolve_implicit_opens<'a, 'b>(
     kind: NameKind,
-    globals: &GlobalScope,
-    namespaces: impl IntoIterator<Item = impl AsRef<str>>,
-    name: &str,
-) -> HashSet<Res> {
+    globals: &'b GlobalScope,
+    namespaces: impl IntoIterator<Item = &'a &'a str>,
+    name: &'b str,
+) -> HashSet<ImplicitOpenResolution<'a>> {
```
Comment (samarsha) [inline compiler/qsc_frontend/src/resolve.rs:757]: The uniqueness is based only on `Res`, and the namespace name is just metadata. This type allows you to return the same `Res` multiple times if the namespace name is different, which is impossible.

That's why `resolve_explicit_opens` returns a `HashMap<Res, &'a Open>` - here it could be `HashMap<Res, &'a str>` (or if you prefer to newtype the string, the struct should contain just the string, not the `Res`).

File: compiler/qsc_frontend/src/resolve.rs [hunk 5]
```diff
@@ -71,6 +71,19 @@ pub(super) enum Error {
     #[error("`{0}` not found")]
     #[diagnostic(code("Qsc.Resolve.NotFound"))]
     NotFound(String, #[label] Span),
+
+    #[error("`{name}` could refer to the item in {candidate_a} or an item in {candidate_b}")]
+    #[diagnostic(help(
+        "a namespace should not be declared with the same name as a namespace in the prelude"
```
[the remark this answers is not in the document]
Comment (samarsha) [reply compiler/qsc_frontend/src/resolve.rs:69]: Maybe something like "both namespaces are implicitly opened by the prelude" in case someone is confused about where the namespaces are coming from?

File: compiler/qsc_frontend/src/resolve.rs [hunk 6]
```diff
@@ -64,6 +64,19 @@ pub(super) enum Error {
...
+    ))]
+    #[diagnostic(code("Qsc.Resolve.AmbiguousPrelude"))]
+    AmbiguousPrelude {
+        name: String,
+        candidate_a: String,
+        candidate_b: String,
+        #[label]
+        span: Span,
```
Comment (samarsha) [inline compiler/qsc_frontend/src/resolve.rs:77]: Not super necessary but I think we might as well keep `Ambiguous` and `AmbiguousPrelude` as similar as possible:

```suggestion
        #[label("ambiguous name")]
        span: Span,
```

**Review by samarsha — APPROVED** [review]
