### PR TITLE
Fix two issues that cause the latest Clippy to fail the build.

### LINKED ISSUE #2256: Clippy - useless_conversion error in qsc_frontend when building the playground locally
#### **Describe the Issue**

Running `./build.py` in the `qsharp` repo fails due to Clippy's `useless_conversion` lint in `qsc_frontend`. This issue prevents building the Playground locally.

#### **Error Message**

```bash
error: useless conversion to the same type: `typeck::convert::TyConversionError`
   --> compiler/qsc_frontend/src/typeck/convert.rs:261:21
    |
261 |            .into_iter()
    |   _____________________^
    |  |_____________________|  
262 | ||         .map(TyConversionError::from)
    | ||_____________________________________^
263 | |          .collect::<Vec<_>>();
    | |_________- help: consider removing
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
    = note: `-D clippy::useless-conversion` implied by `-D warnings`
```

#### **Steps to Reproduce**

1.  Clone the `qsharp` repo.
2.  Run `./build.py` in the root directory.
3.  The build fails due to `clippy::useless_conversion`.

#### **Environment**

-   **Rust Version:** `rustc --version 1.85.1`
-   **Cargo Version:** `cargo --version 1.85.1`
-   **Clippy Version:** `cargo clippy --version  0.1.85`

### PR DESCRIPTION
**Pull request by absoludity**
Remove unnecessary conversion picked up by the latest Clippy in convert.rs

Switch to use .is_none_or instead of .map_or in ast_context.rs.

Fixes #2256

### CODE REVIEW

File: compiler/qsc_frontend/src/typeck/convert.rs [hunk 1]
```diff
@@ -256,11 +256,8 @@ pub(super) fn scheme_for_ast_callable(
     names: &Names,
     callable: &CallableDecl,
 ) -> (Scheme, Vec<TyConversionError>) {
-    let (mut type_parameters, errors) = type_parameters_for_ast_callable(names, &callable.generics);
-    let mut errors = errors
-        .into_iter()
-        .map(TyConversionError::from)
-        .collect::<Vec<_>>();
+    let (mut type_parameters, mut errors) =
+        type_parameters_for_ast_callable(names, &callable.generics);
```
Comment (absoludity) [inline compiler/qsc_frontend/src/typeck/convert.rs:260]: Clippy recommended just removing line 262, but then it's just `errors().into_iter().collect::<Vec<_>>();`, and according to the vscode type hints, `errors` already has the target type - it just needed to be mutable:

Screenshot from 2025-03-28 16-19-04

Regarding the line-break... prettier (which is included by the project) appears to use 80chars as a default... it actually additionally changed a bunch of docstrings as well, but I didn't include those to focus on the actual change here. But let me know if it shouldn't be wrapped here.

**Comment by absoludity** [comment]
@microsoft-github-policy-service agree

**Review by swernli — APPROVED** [review]

**Review by orpuente-MS — APPROVED** [review]
Looks good. Thanks!

**Review by billti — APPROVED** [review]
