### PR TITLE
Minor playground fix

### LINKED ISSUE #3166: run button doesn't work in the playground
https://microsoft.github.io/qdk/

```
main.tsx:74 Received telemetry event: "fetch-wasm" with payload: Object
log.js:29 Worker error: ErrorEvent
error @ log.js:29
9d5fe72d-3533-4f3e-92af-4ca5d84532fc:6 Uncaught SyntaxError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL '/qdk/libs/compiler-worker.js' is invalid.
    at 9d5fe72d-3533-4f3e-92af-4ca5d84532fc:6:7
log.js:29 Worker error: ErrorEvent
error @ log.js:29
920be5aa-255d-4a34-b403-761f18920b62:6 Uncaught SyntaxError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL '/qdk/libs/language-service-worker.js' is invalid.
    at 920be5aa-255d-4a34-b403-761f18920b62:6:7
```

@joao-boechat

### PR DESCRIPTION
**Pull request by joao-boechat**
The worker code was breaking because the worker bootstrap was receiving a relative URL. Now I make sure that it's a absolute URL by transforming the string into a URL first.

### CODE REVIEW

File: source/npm/qsharp/src/workers/adapters/browser.ts [hunk 1]
```diff
@@ -7,7 +7,9 @@ export class BrowserWorkerHost implements IWorkerHost {
   private worker: Worker;
 
   constructor(url: string | URL) {
-    const scriptUrl = typeof url === "string" ? url : url.href;
+    // Make sure the URL is absolute so that importScripts works inside the blob
+    const scriptUrl =
+      typeof url === "string" ? new URL(url, import.meta.url).href : url.href;
```
Comment (billti) [inline source/npm/qsharp/src/workers/adapters/browser.ts:14]: This is confusing to me. `import.meta.url` is only valid in modules, but we bundle. If the bundler is fixing this for the playground/browser somehow, please add a common to make that clear.

**Review by billti — APPROVED** [review]

File: source/npm/qsharp/src/workers/adapters/browser.ts (hunk 1 above)
Comment (joao-boechat) [reply source/npm/qsharp/src/workers/adapters/browser.ts:14]: In `build.js`, the bundler is using `define: { "import.meta.url": "document.URL" },`
I used it that way to make sure it would work in both modules and when bundled. Will add a comment to clarify that.
