### PR TITLE
Fix notebook language service panics

### LINKED ISSUE #873: Panic in notebook language service: "all cells should have been closed along with the notebook"
@billti  hit this with a local build as of 11/22, but we don't have a repro at the moment. 

> Playing around with a latest build with a Notebook and a Q# file, and noticed I wasn't getting the language service any more. Looking in the output channel, seems like it's crashed. Related to recent language service changes for Notebooks maybe, Mine Starks? (I can't recall what I did exactly when it died - sorry)

 ```
2023-11-22 20:27:49.072 [info] Q# extension activated.
2023-11-22 20:27:54.016 [error] Failed to map all utf8 indexes. Remaining indexes are: 1
2023-11-22 20:28:05.443 [error] Failed to map all utf8 indexes. Remaining indexes are: 1
2023-11-22 20:28:10.573 [error] Failed to map all utf8 indexes. Remaining indexes are: 1
2023-11-22 20:28:11.219 [error] Failed to map all utf8 indexes. Remaining indexes are: 1
2023-11-22 20:30:24.091 [error] [%s] Wasm panic occurred: panicked at /home/vsts/work/1/s/language_service/src/lib.rs:227:13:
all cells should have been closed along with the notebook
 
Stack:
 
Error:
    at imports.wbg.__wbg_new_0232637a3cb0b1a7 (file:///Users/billti/.vscode-insiders/extensions/quantum.qsharp-lang-vscode-dev-1.0.23/out/extension.js#vscode-extension:31146:17)
    at wasm://wasm/006d859a:wasm-function[2005]:0x15d67d
    at wasm://wasm/006d859a:wasm-function[1016]:0x129ae1
    at wasm://wasm/006d859a:wasm-function[1556]:0x14d354
    at wasm://wasm/006d859a:wasm-function[569]:0xfa771
    at _LanguageService.close_notebook_document (file:///Users/billti/.vscode-insiders/extensions/quantum.qsharp-lang-vscode-dev-1.0.23/out/extension.js#vscode-extension:30985:10)
    at QSharpLanguageService.closeNotebookDocument (file:///Users/billti/.vscode-insiders/extensions/quantum.qsharp-lang-vscode-dev-1.0.23/out/extension.js#vscode-extension:31863:26)
    at closeIfKnownQsharpNotebook (file:///Users/billti/.vscode-insiders/extensions/quantum.qsharp-lang-vscode-dev-1.0.23/out/extension.js#vscode-extension:35028:23)
    at updateIfQsharpNotebook (file:///Users/billti/.vscode-insiders/extensions/quantum.qsharp-lang-vscode-dev-1.0.23/out/extension.js#vscode-extension:35021:9)
    at R.eval [as value] (file:///Users/billti/.vscode-insiders/extensions/quantum.qsharp-lang-vscode-dev-1.0.23/out/extension.js#vscode-extension:34995:7)
```

### PR DESCRIPTION
**Pull request by minestarks**
Fixes #873

ISSUE 1 (#873):

`close_notebook_document` takes both the notebook URI and a list of cell URIs, which is redundant, since we should already know in the language service which cells belong to the notebook. We still had an assert to verify that these two parameters were being sent consistently - and it turns out they weren't. When the last Q# cell in a notebook is deleted, we send `close_notebook_document` with _no_ Q# cells (instead of the last known list). That tripped the assert.

I'm just removing the redundant `cell_uris` parameter and using the open document map instead.

ISSUE 2 (new panic):

I'm 99.99% sure this is a change in VS Code, since this panic is so trivial to hit. All you have to do is close a notebook. I tried with builds of `qsharp` from September, and I still hit it. Basically, using `vscode.languages.match()` to determine whether a notebook cell is Q# is very unreliable, as it returns no match if the notebook is being closed. This leads to a panic in the language service. So instead I'm just using the `languageId` and `scheme` - same logic, much simpler.

### CODE REVIEW

File: language_service/src/state.rs [hunk 1]
```diff
@@ -313,32 +313,19 @@ impl<'a> CompilationStateUpdater<'a> {
...
-            for open_doc in state.open_documents.values() {
-                assert!(
-                    notebook_uri != open_doc.compilation.as_ref(),
-                    "all cells should have been closed along with the notebook"
-                );
-            }
+            // First remove all the cells for the notebook
+            state
+                .open_documents
+                .retain(|_, open_doc| notebook_uri != open_doc.compilation.as_ref());
```
Comment (billti) [inline language_service/src/state.rs:323]: Maybe it's just my lack of understanding, but it's not clear to me how the code maps to the comment.

**Review by billti — APPROVED** [review]

**Review by swernli — APPROVED** [review]

**Review by cesarzc — APPROVED** [review]
