### PR TITLE
Fix out-of-memory in typeck on nested `Ty::Arrow`

### LINKED ISSUE #2302: Fuzz: out-of-memory in typeck and hir lowering
The fuzz-testing workflow has detected a bug.

<details><summary><b>Auto-Minimized Fuzzing Input That Triggers the Bug:</b> Click this line.</summary>
<b>Note:</b> If the input is multi-line then the end-of-line characters '\n' (0x0A) and '\r' (0x0D)
may affect the reproducibility of the bug. If you fail to repro the bug with the input shown below
then you may want to go to the <a href=https://github.com/microsoft/qsharp/actions/runs/14499191698>workflow</a> that reported this GitHub bug,
download the artifact, and extract the file with the exact minimized input.

```openqasm
pow(0)@pow(5)@ pow(0.)@pow(5)@ pow(.5)@ pow(0)@pow(0)o@ pow(0) @pow(0.) @pow(5) @ pow(0)@ pow(0)p@pow(5)@ pow(5)@pow(5)t@pow(0) @pow(0)@pow(.5)@ pow(5)@ pow(.5)@p
```

</details>

<details><summary><b>Fuzzing <code>stderr</code> Log</b> (last 62kB), includes the stack trace: Click.</summary>
The fragment of interest starts with "panicked at".

```gdb


Failing input:

	fuzz/artifacts/qasm3/oom-a2e788702a85968e356f1e32929c98f2b05b9a66

Output of `std::fmt::Debug`:

	[47, 47, 32, 79, 112, 101, 110, 81, 65, 83, 77, 32, 51, 46, 48, 32, 115, 116, 97, 110, 100, 97, 114, 100, 32, 103, 97, 1, 0, 0, 0, 0, 0, 0, 18, 114, 121, 10, 47, 47, 10, 47, 47, 32, 78, 111, 116, 101, 58, 32, 116, 104, 101, 32, 103, 97, 45, 207, 128, 47, 52, 41, 59, 125, 10, 47, 47, 58, 32, 105, 110, 118, 101, 114, 115, 101, 32, 111, 102, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 110, 100, 97, 114, 100, 32, 103, 97, 116, 101, 32, 108, 105, 98, 114, 97, 114, 121, 10, 47, 47, 10, 47, 47, 32, 78, 111, 116, 101, 58, 32, 116, 104, 101, 32, 103, 97, 45, 207, 128, 47, 52, 41, 59, 125, 10, 47, 47, 58, 32, 105, 110, 118, 101, 114, 115, 101, 32, 111, 102, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 115, 0, 0, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 108, 101, 109, 101, 110, 116, 97, 116, 105, 111, 110, 115, 10, 47, 47, 32, 104, 97, 118, 101, 32, 115, 111, 109, 101, 32, 115, 99, 111, 112, 101, 32, 102, 111, 114, 32, 104, 111, 119, 32, 116, 104, 101, 121, 32, 104, 97, 110, 100, 108, 101, 32, 116, 104, 101, 32, 102, 105, 108, 101, 32, 105, 110, 116, 101, 114, 110, 97, 108, 78, 111, 116, 101, 58, 32, 116, 104, 101, 32, 103, 97, 45, 207, 128, 47, 52, 41, 59, 125, 10, 47, 47, 58, 32, 105, 110, 118, 101, 114, 115, 101, 32, 111, 102, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 53, 48, 46, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 110, 100, 97, 114, 100, 32, 103, 97, 116, 101, 32, 108, 105, 98, 114, 97, 114, 121, 10, 47, 47, 10, 47, 47, 32, 78, 111, 116, 101, 58, 32, 116, 104, 101, 32, 103, 97, 45, 207, 128, 47, 52, 41, 59, 125, 10, 47, 47, 58, 32, 105, 110, 118, 101, 114, 115, 101, 32, 111, 102, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 108, 101, 109, 101, 110, 116, 97, 116, 105, 111, 110, 115, 10, 47, 47, 32, 104, 97, 118, 101, 32, 115, 111, 109, 101, 32, 115, 99, 111, 112, 101, 32, 102, 111, 114, 32, 104, 111, 119, 32, 116, 104, 101, 121, 32, 104, 97, 110, 100, 108, 101, 32, 116, 104, 101, 32, 102, 105, 108, 101, 32, 105, 110, 116, 101, 114, 110, 97, 108, 78, 32, 102, 105, 108, 101, 32, 105, 110, 116, 101, 114, 110, 97, 108, 78, 111, 116, 101, 58, 32, 116, 104, 101, 32, 103, 97, 45, 207, 128, 47, 52, 41, 59, 125, 10, 47, 47, 58, 32, 105, 110, 118, 101, 114, 115, 101, 32, 111, 102, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 108, 101, 109, 101, 110, 116, 97, 116, 105, 111, 110, 115, 10, 47, 47, 32, 104, 97, 118, 101, 32, 115, 111, 109, 101, 32, 115, 99, 111, 112, 101, 32, 102, 111, 114, 32, 104, 111, 119, 32, 116, 104, 101, 121, 32, 104, 97, 110, 100, 108, 101, 32, 116, 104, 101, 32, 102, 105, 108, 101, 32, 105, 110, 116, 101, 114, 110, 97, 108, 78, 32, 102, 105, 108, 101, 32, 105, 110, 116, 101, 114, 110, 97, 108, 78, 111, 116, 101, 58, 32, 116, 104, 101, 32, 103, 97, 45, 207, 128, 47, 52, 41, 59, 125, 10, 47, 47, 58, 32, 105, 110, 118, 101, 114, 115, 101, 32, 111, 102, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 108, 101, 109, 101, 110, 116, 97, 116, 105, 111, 110, 115, 10, 47, 47, 32, 104, 97, 118, 101, 32, 115, 111, 109, 101, 32, 115, 99, 111, 112, 101, 32, 102, 111, 114, 32, 104, 111, 119, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 110, 100, 97, 114, 100, 32, 103, 97, 116, 101, 32, 108, 105, 98, 114, 97, 114, 121, 10, 47, 47, 10, 47, 47, 32, 78, 111, 116, 101, 58, 32, 116, 104, 101, 32, 103, 97, 45, 207, 128, 47, 52, 41, 59, 125, 10, 47, 47, 58, 32, 105, 110, 118, 101, 114, 115, 101, 32, 111, 102, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 115, 44, 32, 98, 117, 116, 32, 105, 109, 112, 108, 101, 109, 101, 110, 116, 97, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 100, 101, 102, 105, 110, 101, 100, 44, 32, 97, 115, 32, 97, 114, 101, 32, 116, 104, 101, 32, 117, 110, 105, 116, 97, 114, 121, 32, 97, 99, 116, 105, 111, 110, 116, 105, 111, 110, 115, 10, 47, 47, 32, 104, 97, 118, 101, 32, 115, 111, 109, 101, 32, 115, 99, 111, 112, 101, 32, 102, 111, 114, 32, 104, 111, 119, 32, 116, 104, 101, 121, 32, 104, 97, 110, 100, 108, 101, 32, 116, 104, 101, 32, 102, 105, 108, 101, 32, 105, 110, 116, 101, 114, 110, 97, 108, 78, 111, 116, 101, 58, 32, 116, 104, 101, 32, 103, 97, 45, 207, 128, 47, 52, 41, 59, 125, 10, 47, 47, 58, 32, 105, 110, 118, 101, 114, 115, 101, 32, 111, 102, 32, 115, 113, 114, 116, 40, 90, 41, 10, 103, 97, 116, 101, 32, 115, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 101, 99, 105, 102, 100, 103, 32, 97, 32, 123, 32, 105, 110, 118, 32, 64, 32, 112, 111, 119, 40, 48, 46, 53, 41, 32, 47, 32, 51, 46, 48, 32, 115, 112, 114, 97, 114, 121, 46, 114, 115, 116, 96, 32, 100, 111, 99, 117, 109, 101, 110, 116, 97, 116, 105, 111, 47, 108, 97, 110, 103, 117, 97, 103, 101, 47, 115, 116, 97, 110, 100, 97, 114, 100, 95, 108, 105, 98, 114, 97, 114, 121, 46, 114, 115, 116, 96, 32, 100, 111, 99, 32, 103, 97, 116, 101, 10, 103, 97, 116, 123, 32, 99, 116, 114, 108, 32, 64, 32, 103, 112, 104, 97, 115, 101, 40, 206, 187, 41, 32, 97, 59, 32, 125, 10, 10, 47, 47, 32, 80, 97, 40, 45, 206, 187, 47, 50, 41, 59, 32, 117, 108, 105]

Reproduce with:

	cargo fuzz run -O --features=do_fuzz --sanitizer=none qasm3 fuzz/artifacts/qasm3/oom-a2e788702a85968e356f1e32929c98f2b05b9a66

Minimize test case with:

	cargo fuzz tmin -O --features=do_fuzz --sanitizer=none qasm3 fuzz/artifacts/qasm3/oom-a2e788702a85968e356f1e32929c98f2b05b9a66

────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit status: 71

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: cargo_fuzz::project::FuzzProject::exec_fuzz
   2: cargo_fuzz::main
   3: std::sys::backtrace::__rust_begin_short_backtrace
   4: std::rt::lang_start::{{closure}}
   5: std::rt::lang_start_internal
   6: main
   7: <unknown>
   8: __libc_start_main
   9: _start
```

</details>

<details><summary><b>The branch/commit the bug has been found in:</b> Click.</summary>
If the developers fail to repro the bug in the latest <code>main</code> then the branch/commit info below can help them to make sure
that they are using the correct way to repro. If the bug is reproducible in the branch/commit below, but not in latest <code>main</code>,
then the bug is likely fixed already or is not in the <code>main</code> branch.

```log
Branch: * iadavis/qasm-fuzz

commit e69eb7b8c2639ac4ba9eed6e0ffb6fbb1ff7e342
Author: Ian Davis <ian.f.davis@microsoft.com>
Date:   Wed Apr 16 10:50:02 2025 -0700

    Adding more compilation and samples for fuzzing
```

</details>

**Other Info**

- [**Workflow**](https://github.com/microsoft/qsharp/actions/runs/14499191698) (contains the run artifacts).
- **Workflow Agent System Info:** `ubuntu-latest: Linux fv-az1781-260 6.8.0-1021-azure #25-Ubuntu SMP Wed Jan 15 20:45:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`.
- **Bug Reporting Timestamp:** 2025.04.16 20:04 UTC (UTC - 8:00 = PST. UTC - 7:00 = PDT).
- [Playground reproduction](https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAAE41SQW%252BCMBi98yvezTZriDt4wc3MOA8eZlzmTsaQMqrWIO1qzWYM%252F30pOEC2Mb8D8Pr63usDHsapNceZkqkl1FNaGG6lSqGNWhu%252BIxQBXlNpcfIAQO60MhYvNvafuN34w2g%252F6edMJQ3DmfoIw7vOfECmCDBJLYPSCEA6c9wPCj%252B5xzDe4gYjm1AGy81aWATozBuRbhJhncM95ApTDNDFCYQ6L6VJIaXIIJK9KJlhvHWtLnb0S8eVMgghU9z6eQkypbW8ohCh5ULmVdeq6Vpv%252BF4QuxGWI8CjOkSJKI9fb1jzjlR8hO%252F7jbjxpyaLJUNuxrBYNsPd8HMnfrCq6vKmUmtUkoi4hfihzLxGG00SvoviqgnD%252ByGS7qM8u%252Ft%252FxUZV2vnFLHL9kqEwphfB59%252BEdNn3IwPp1UHXb6Eu4ZWgxfBP0LsOtKW2qBynGQj9bfpe5nlfguLqj6IDAAA%253D&profile=unrestricted)

### PR DESCRIPTION
**Pull request by swernli**
This change updates the `Ty::Arrow` enum variant to use `Rc` which allows sharing of instances of callable types within the type infrastructure. To allow mutability during type inference, the underlying `Arrow` struct now uses `RefCell` for it's contained type and relies on runtime borrow checking for mutability.

Fixes #2302

### CODE REVIEW

**Comment by swernli** [comment]
Benchmarks against baseline from main seem promising. Evaluation benches remain the same (expected since those measure execution time). Compilation benches show 4-8% improvement:
```text
Benchmarking Large input file compilation: Collecting 100 samples in estima
Large input file compilation
                        time:   [6.4109 ms 6.4185 ms 6.4274 ms]
                        change: [-8.3411% -8.1384% -7.9460%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe

Benchmarking Large input file compilation (interpreter): Warming up for 3.0
Benchmarking Large input file compilation (interpreter): Collecting 100 sam
Large input file compilation (interpreter)
                        time:   [27.505 ms 27.528 ms 27.557 ms]
                        change: [-4.3618% -4.1526% -3.9671%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe

     Running benches/library.rs (target/release/deps/library-efc5d4dc899ee30b)
Benchmarking Core + Standard library compilation: Collecting 100 samples in
Core + Standard library compilation
                        time:   [12.335 ms 12.349 ms 12.368 ms]
                        change: [-4.8064% -4.5325% -4.2903%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  2 (2.00%) high mild
  3 (3.00%) high severe
```

**Review by orpuente-MS — APPROVED** [review]

File: compiler/qsc_frontend/src/typeck/convert.rs [hunk 1]
```diff
@@ -290,15 +290,24 @@ pub(crate) fn synthesize_functor_params(
...
-                let param = HirTypeParameter::Functor(functors);
-                arrow.functors = FunctorSet::Param(*next_param, functors);
-                *next_param = next_param.successor();
-                vec![param]
+        Ty::Arrow(arrow) => {
+            let functors = *arrow.functors.borrow();
+            match functors {
+                FunctorSet::Value(functors) if arrow.kind == hir::CallableKind::Operation => {
+                    let param = HirTypeParameter::Functor(functors);
+                    // This uses `RefCell::replace` to update the functor set within the refernce counted arrow.
```
Comment (idavis) [inline compiler/qsc_frontend/src/typeck/convert.rs:298]:
```suggestion
                    // This uses `RefCell::replace` to update the functor set within the reference counted arrow.
```

File: compiler/qsc_frontend/src/typeck/tests.rs [hunk 2]
```diff
@@ -4695,3 +4695,52 @@ fn field_access_not_ident() {
         "##]],
     );
 }
+
+#[test]
+fn stressing_generic_inference() {
```
Comment (minestarks) [inline compiler/qsc_frontend/src/typeck/tests.rs:4700]: Should this be in the benches instead of a unit test? (Since the bug is really about perf -  if we regress this scenario badly, we may not notice it if it's just another unit test, but we'd notice the perf regression if it was in the benches)

File: compiler/qsc_frontend/src/typeck/tests.rs [hunk 3]
```diff
@@ -4695,3 +4695,52 @@ fn field_access_not_ident() {
...
+    check(
+        indoc! {r#"
+            namespace Test {
+                function swap<'T1, 'T2>(op : ('T1, 'T2) -> ('T2, 'T1), input: ('T1, 'T2)) : ('T2, 'T1) {
+                    op(input)
+                }
+                function nested_swaps() : Unit {
+                    // let a = swap(swap(swap(swap(swap(swap(swap(swap(swap(swap(swap(swap(swap(swap(swap(_)))))))))))))));
```
Comment (minestarks) [inline compiler/qsc_frontend/src/typeck/tests.rs:4708]: Did you mean to leave this commented out?

File: compiler/qsc_frontend/src/typeck/tests.rs [hunk 4]
```diff
@@ -4695,3 +4695,52 @@ fn field_access_not_ident() {
...
+                    let a = swap(swap(swap(swap(_))));
```
Comment (ScottCarda-MS) [inline compiler/qsc_frontend/src/typeck/tests.rs:4709]: Looks like you have two versions of the test here, with the significantly longer one commented out.

File: compiler/qsc_frontend/src/lower/tests.rs [hunk 5]
```diff
@@ -1436,7 +1436,7 @@ fn lambda_operation_closure() {
                         body: SpecDecl 9 [80-130]: Impl:
                             Block 10 [122-130] [Type Result]:
                                 Stmt 11 [124-128]: Expr: Expr 12 [124-128] [Type Result]: Call:
-                                    Expr 13 [124-126] [Type (Unit => Result)]: Var: Local 8
+                                    Expr 13 [124-126] [Type (Unit => Result is Param<0>)]: Var: Local 8
```
Comment (ScottCarda-MS) [inline compiler/qsc_frontend/src/lower/tests.rs:1439]: Both of the changed tests in here reference an empty functor set. Do we have tests that reference non-empty functor set generic parameters?

**Review by ScottCarda-MS — APPROVED** [review]

File: compiler/qsc_frontend/src/typeck/infer.rs [hunk 6]
```diff
@@ -1018,27 +1052,32 @@ fn check_ctl(op: Ty, with_ctls: Ty, span: Span) -> (Vec<Constraint>, Vec<Error>)
...
                 actual: with_ctls,
                 span,
             },
         ],
         Vec::new(),
-    )
+    );
+    #[allow(
+        clippy::let_and_return,
+        reason = "rust requires the explicit let-biding to satisfy lifetime guarantees"
```
Comment (minestarks) [inline compiler/qsc_frontend/src/typeck/infer.rs:1078]:
```suggestion
        reason = "rust requires the explicit let-binding to satisfy lifetime guarantees"
```

Comment (minestarks) [reply compiler/qsc_frontend/src/typeck/infer.rs:1078]: Actually, you don't even need the clippy suppression if you just pull the `*arrow` access out of this expression, and return the expression directly:

```rust
    let actual = *arrow.functors.borrow();
    (
        vec![
            Constraint::Superset {
                expected: FunctorSetValue::Ctl,
                actual,
                span,
            },
            Constraint::Eq {
                expected: Ty::Arrow(Rc::new(Arrow {
                    kind: arrow.kind,
                    input: ctl_input,
                    output: arrow.output.clone(),
                    functors: arrow.functors.clone(),
                })),
                actual: with_ctls,
                span,
            },
        ],
        Vec::new(),
    )
```

**Review by minestarks — APPROVED** [review]
Honestly, the introduction of `Rc` and dynamic borrowing makes me really nervous in this PR, but I don't understand the typechecking code nearly well enough to suggest an alternative. The tests pass, so... 👍

File: compiler/qsc_frontend/src/lower/tests.rs (hunk 5 above)
Comment (swernli) [reply compiler/qsc_frontend/src/lower/tests.rs:1439]: oh, actually, the one right after this just needs to be updated to include a usage of the passed in adjoint operation.

Comment (ScottCarda-MS) [reply compiler/qsc_frontend/src/lower/tests.rs:1439]: It makes sense that the reference here is always a reference to the functor generic. And there are tests where that functor generic is non-empty, which is what I was asking about. Thanks!

File: compiler/qsc_frontend/src/typeck/tests.rs [hunk 7]
```diff
@@ -4319,9 +4319,9 @@ fn inference_infinite_recursion_should_fail() {
...
+            #50 180-187 "A and B" : (((?1[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][], ?3) -> ?1[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]) -> ?1[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][])
+            #51 180-181 "A" : (((?1[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][], ?3) -> ?1[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]) -> ?1[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][])
```
[the remark this answers is not in the document]
Comment (swernli) [reply compiler/qsc_frontend/src/typeck/tests.rs:4324]: This one is a funny one... because the callable types are refrences now, they "see" updates that previously would not have propagated to the earlier usage by the time the type inference recursion runs out. Within the infrastructure, we have logic that tries to repeatedly go through the outstanding generics and replace them with the inferred types. Previously this display showed the type partway through one of those updates (where a "further down" copy of the generic was updated but this one wasn't yet). Now that the arrow types are references, updating one automatically updates all it's uses such that we see the result of more updates. Hopefully that word salad made sense...

File: compiler/qsc_frontend/src/typeck/tests.rs (hunk 3 above)
Comment (swernli) [reply compiler/qsc_frontend/src/typeck/tests.rs:4708]: whoops, left behind by mistake!

File: compiler/qsc_frontend/src/typeck/tests.rs (hunk 4 above)
Comment (swernli) [reply compiler/qsc_frontend/src/typeck/tests.rs:4709]: Nope, left behind by mistake.

File: compiler/qsc_frontend/src/typeck/tests.rs (hunk 2 above)
Comment (swernli) [reply compiler/qsc_frontend/src/typeck/tests.rs:4700]: That's a good question... I suppose it makes more sense as a benchmark, but also we don't pay that close attention to the benchmarks these days. Still, seems worth moving it since it is a better fit there.

Comment (swernli) [reply compiler/qsc_frontend/src/typeck/tests.rs]: Moved into type checking benchmark.

File: compiler/qsc_frontend/src/typeck/infer.rs (hunk 6 above)
Comment (swernli) [reply compiler/qsc_frontend/src/typeck/infer.rs]: Good call, that is a nicer solution.

**Comment by swernli** [comment]
@microsoft-github-policy-service rerun
