### PR TITLE
Disallow whitespace or comments between an Apos and the following Ident

### LINKED ISSUE #407: Parser allows type parameters to have whitespace after apostrophe
Type parameters like `'T` are allowed to be written as `'       T`, or even:

```
' // comment
T
```

which is kind of confusing. The old compiler only allowed the identifier to be directly adjacent to the apostrophe. To enforce this, we would need to change the lexer (and probably just the cooked lexer) to create a single token for `'T` that can't be split by whitespace.

### LINKED ISSUE #468: Fuzz: "internal error: entered unreachable code: A path should never resolve to a local or a parameter, as there is syntactic differentiation." (ubuntu-latest)
The fuzz-testing workflow has detected a bug.

<details><summary><b>Auto-Minimized Fuzzing Input That Triggers the Bug:</b> Click this line.</summary>
<b>Note:</b> If the input is multi-line then the end-of-line characters '\n' (0x0A) and '\r' (0x0D)
may affect the reproducibility of the bug. If you fail to repro the bug with the input shown below
then you may want to go to the <a href=https://github.com/microsoft/qsharp/actions/runs/5589902233>workflow</a> that reported this GitHub bug,
download the artifact, and extract the file with the exact minimized input.

```qs
namespace o{function p<'B>(a:B):e{
```

</details>

<details><summary><b>Fuzzing <code>stderr</code> Log</b> (last 62kB), includes the stack trace: Click.</summary>
The fragment of interest starts with "panicked at".

```gdb
zzer-sys-0.4.6/libfuzzer/FuzzerLoop.cpp:903:21
  33: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/libfuzzer/FuzzerDriver.cpp:912:10
  34: main
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.6/libfuzzer/FuzzerMain.cpp:20:30
  35: <unknown>
  36: __libc_start_main
  37: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
==4264== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 4 CMP-CrossOver-ChangeByte-ChangeBit- DE: "\001\000\000\000\000\000\000\000"-; base unit: b96d12553199f7c784d7319f10069815c872eb77
artifact_prefix='/home/runner/work/qsharp/qsharp/fuzz/artifacts/compile/'; Test unit written to /home/runner/work/qsharp/qsharp/fuzz/artifacts/compile/crash-329783cbc2fd0828840d6c289adc83a0bc2bb478

────────────────────────────────────────────────────────────────────────────────

Failing input:

	fuzz/artifacts/compile/crash-329783cbc2fd0828840d6c289adc83a0bc2bb478

Output of `std::fmt::Debug`:

	[239, 187, 191, 47, 47, 32, 67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 40, 99, 41, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 67, 111, 114, 112, 111, 114, 97, 116, 105, 111, 110, 46, 32, 65, 108, 108, 32, 114, 105, 103, 104, 116, 115, 32, 114, 101, 115, 101, 114, 118, 101, 100, 46, 10, 47, 47, 32, 76, 105, 99, 101, 110, 115, 101, 100, 32, 117, 110, 100, 101, 114, 32, 116, 104, 101, 32, 77, 73, 84, 32, 76, 105, 99, 101, 110, 115, 101, 46, 10, 10, 47, 47, 47, 32, 84, 104, 105, 115, 32, 110, 97, 109, 101, 115, 112, 97, 99, 101, 32, 99, 111, 110, 116, 97, 105, 110, 115, 32, 116, 101, 115, 116, 32, 99, 97, 115, 101, 115, 32, 102, 111, 114, 32, 101, 120, 112, 114, 101, 115, 115, 105, 111, 110, 32, 97, 110, 100, 32, 115, 116, 97, 116, 101, 109, 101, 110, 116, 32, 118, 101, 114, 105, 102, 105, 99, 97, 116, 105, 111, 110, 10, 110, 97, 109, 101, 115, 112, 97, 99, 101, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 84, 101, 115, 116, 105, 110, 103, 46, 76, 111, 99, 97, 108, 86, 101, 114, 105, 102, 105, 99, 97, 116, 105, 111, 110, 32, 123, 10, 32, 32, 32, 32, 111, 112, 101, 110, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 68, 105, 97, 103, 110, 111, 115, 116, 105, 99, 115, 59, 10, 32, 32, 32, 32, 111, 112, 101, 110, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 84, 101, 115, 116, 105, 110, 103, 46, 71, 101, 110, 101, 114, 97, 108, 59, 10, 32, 32, 32, 32, 111, 112, 101, 110, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 84, 101, 115, 116, 105, 110, 103, 46, 84, 121, 112, 101, 67, 104, 101, 99, 107, 105, 110, 103, 59, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 85, 110, 117, 115, 101, 100, 84, 121, 112, 101, 80, 97, 114, 97, 109, 60, 39, 97, 62, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 83, 101, 113, 117, 101, 110, 99, 101, 60, 39, 97, 44, 32, 39, 98, 62, 40, 102, 32, 58, 32, 39, 97, 32, 61, 62, 32, 85, 110, 105, 116, 44, 32, 103, 32, 58, 32, 39, 98, 32, 61, 62, 32, 85, 110, 105, 116, 41, 32, 58, 32, 40, 39, 97, 44, 32, 39, 98, 41, 32, 61, 62, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 34, 78, 111, 116, 32, 105, 109, 112, 108, 101, 109, 101, 110, 116, 101, 100, 46, 34, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 47, 47, 32, 116, 121, 112, 101, 32, 97, 114, 103, 117, 109, 101, 110, 116, 32, 105, 110, 102, 101, 114, 101, 110, 99, 101, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 114, 101, 99, 117, 114, 32, 61, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 40, 51, 44, 32, 95, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 99, 117, 114, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 116, 117, 112, 108, 101, 32, 61, 32, 40, 49, 44, 32, 40, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 40, 51, 44, 32, 95, 41, 44, 32, 34, 34, 41, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 40, 95, 44, 32, 40, 114, 101, 99, 117, 114, 44, 32, 95, 41, 41, 32, 61, 32, 116, 117, 112, 108, 101, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 99, 117, 114, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 40, 49, 44, 32, 95, 41, 44, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 40, 95, 44, 32, 97, 114, 103, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 40, 49, 44, 32, 95, 41, 44, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 40, 95, 44, 32, 97, 114, 103, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 53, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 53, 40, 49, 44, 32, 95, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 95, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 53, 40, 49, 44, 32, 95, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 54, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 54, 40, 49, 44, 32, 95, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 55, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 43, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 55, 40, 49, 44, 32, 95, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 56, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 56, 40, 49, 44, 32, 95, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 46, 46, 32, 48, 32, 60, 45, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 56, 40, 49, 44, 32, 95, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 57, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 102, 111, 111, 32, 61, 32, 97, 114, 114, 32, 119, 47, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 57, 40, 49, 44, 32, 95, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 98, 97, 114, 32, 61, 32, 97, 114, 114, 32, 119, 47, 32, 48, 32, 46, 46, 32, 48, 32, 60, 45, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 57, 40, 49, 44, 32, 95, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 102, 111, 111, 91, 48, 93, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 48, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 114, 32, 114, 91, 97, 32, 32, 61, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 43, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 50, 40, 95, 44, 32, 97, 114, 103, 41, 44, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 50, 40, 95, 44, 32, 34, 34, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 49, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 114, 49, 32, 61, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 49, 40, 95, 44, 32, 34, 34, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 114, 101, 99, 117, 114, 32, 61, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 49, 40, 95, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 99, 117, 114, 40, 99, 110, 116, 32, 45, 32, 49, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 50, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 116, 49, 32, 61, 32, 40, 49, 44, 32, 40, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 50, 40, 95, 44, 32, 49, 41, 44, 32, 34, 34, 41, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 116, 117, 112, 108, 101, 32, 61, 32, 40, 49, 44, 32, 40, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 50, 40, 95, 44, 32, 97, 114, 103, 41, 44, 32, 34, 34, 41, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 40, 95, 44, 32, 40, 114, 101, 99, 117, 114, 44, 32, 95, 41, 41, 32, 61, 32, 116, 117, 112, 108, 101, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 99, 117, 114, 40, 99, 110, 116, 32, 45, 32, 49, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 51, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 51, 40, 95, 44, 32, 97, 114, 103, 41, 44, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 51, 40, 95, 44, 32, 49, 46, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 95, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 51, 40, 95, 44, 32, 97, 114, 103, 41, 44, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 51, 40, 95, 44, 32, 49, 46, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 52, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 52, 40, 95, 44, 32, 80, 97, 117, 108, 105, 88, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 52, 40, 95, 44, 32, 97, 114, 103, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 53, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 43, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 53, 40, 95, 44, 32, 80, 97, 117, 108, 105, 88, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 43, 61, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 53, 40, 95, 44, 32, 97, 114, 103, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 49, 93, 40, 99, 110, 116, 32, 45, 32, 49, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 54, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 73, 110, 116, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 54, 40, 95, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 54, 40, 95, 44, 32, 53, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 55, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 73, 110, 116, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 50, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 46, 46, 32, 49, 32, 60, 45, 32, 91, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 55, 40, 95, 44, 32, 97, 114, 103, 41, 44, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 54, 40, 95, 44, 32, 97, 114, 103, 41, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 56, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 73, 110, 116, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 102, 111, 111, 32, 61, 32, 97, 114, 114, 32, 119, 47, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 56, 40, 95, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 98, 97, 114, 32, 61, 32, 97, 114, 114, 32, 119, 47, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 56, 40, 95, 44, 32, 90, 101, 114, 111, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 57, 60, 39, 84, 62, 40, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 39, 84, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 49, 57, 60, 39, 84, 62, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 48, 60, 39, 84, 62, 40, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 39, 84, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 48, 40, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 49, 60, 39, 65, 62, 40, 97, 32, 58, 32, 39, 65, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 49, 60, 39, 65, 62, 40, 51, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 50, 60, 39, 65, 62, 40, 97, 32, 58, 32, 39, 65, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 50, 60, 73, 110, 116, 62, 40, 97, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 39, 65, 44, 32, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 95, 44, 95, 62, 40, 97, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 52, 60, 39, 65, 44, 32, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 52, 60, 39, 65, 44, 39, 66, 62, 40, 97, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 53, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 73, 110, 116, 32, 45, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 53, 60, 73, 110, 116, 44, 32, 95, 62, 40, 95, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 54, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 39, 65, 32, 45, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 54, 60, 39, 65, 44, 32, 95, 62, 40, 95, 44, 32, 52, 46, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 55, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 55, 60, 39, 65, 44, 32, 95, 62, 40, 49, 44, 32, 52, 46, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 56, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 56, 60, 95, 44, 32, 73, 110, 116, 62, 40, 97, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 57, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 57, 60, 39, 65, 44, 32, 39, 65, 62, 40, 97, 44, 32, 97, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 48, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 48, 60, 39, 65, 44, 32, 39, 65, 62, 40, 97, 44, 32, 51, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 49, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 49, 60, 39, 65, 44, 32, 39, 65, 62, 40, 97, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 50, 60, 39, 65, 62, 40, 97, 32, 58, 32, 39, 65, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 49, 60, 39, 65, 62, 40, 51, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 51, 60, 39, 65, 62, 40, 97, 32, 58, 32, 39, 65, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 49, 60, 73, 110, 116, 62, 40, 97, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 52, 60, 39, 65, 44, 32, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 95, 44, 95, 62, 40, 97, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 53, 60, 39, 65, 44, 32, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 7, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 39, 65, 44, 39, 66, 62, 40, 97, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 0, 0, 0, 0, 0, 0, 0, 15, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 54, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 73, 110, 116, 32, 45, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 73, 110, 116, 44, 32, 95, 62, 40, 95, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 55, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 39, 65, 32, 45, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 60, 45, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 60, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 39, 65, 44, 32, 95, 62, 40, 95, 44, 32, 52, 46, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 56, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 39, 65, 44, 32, 95, 62, 40, 49, 44, 32, 52, 46, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 51, 57, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 95, 44, 32, 73, 110, 116, 62, 40, 97, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 48, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 39, 65, 44, 32, 39, 65, 62, 40, 97, 44, 32, 97, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 49, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 39, 65, 44, 32, 39, 65, 62, 40, 97, 44, 32, 51, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 50, 60, 39, 65, 44, 39, 66, 62, 40, 97, 32, 58, 32, 39, 65, 44, 32, 98, 32, 58, 32, 39, 66, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 50, 51, 60, 39, 65, 44, 32, 39, 65, 62, 40, 97, 44, 32, 98, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 51, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 68, 101, 102, 97, 117, 108, 116, 40, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 52, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 95, 32, 61, 32, 68, 101, 102, 97, 117, 108, 116, 40, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 53, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 85, 110, 117, 115, 101, 100, 84, 121, 112, 101, 80, 97, 114, 97, 109, 40, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 54, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 95, 32, 61, 32, 71, 101, 110, 101, 114, 105, 99, 70, 117, 110, 99, 116, 105, 111, 110, 40, 68, 101, 102, 97, 117, 108, 116, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 121, 112, 101, 65, 114, 103, 117, 109, 101, 110, 116, 115, 73, 110, 102, 101, 114, 101, 110, 99, 101, 52, 55, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 83, 101, 113, 117, 101, 110, 99, 101, 40, 71, 101, 110, 101, 114, 105, 99, 79, 112, 101, 114, 97, 116, 105, 111, 110, 44, 32, 71, 101, 110, 101, 114, 105, 99, 79, 112, 101, 114, 97, 116, 105, 111, 110, 41, 40, 34, 70, 111, 111, 34, 44, 32, 51, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 47, 47, 32, 118, 97, 114, 105, 97, 98, 108, 101, 32, 100, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 115, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 113, 32, 61, 32, 81, 117, 98, 105, 116, 40, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 50, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 113, 32, 61, 32, 40, 81, 117, 98, 105, 116, 40, 41, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 51, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 40, 113, 41, 32, 61, 32, 81, 117, 98, 105, 116, 40, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 52, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 40, 113, 41, 32, 61, 32, 40, 81, 117, 98, 105, 116, 40, 41, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 53, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 40, 113, 49, 44, 32, 113, 50, 41, 32, 61, 32, 40, 81, 117, 98, 105, 116, 40, 41, 44, 32, 81, 117, 98, 105, 116, 40, 41, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 54, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 40, 113, 49, 44, 32, 40, 113, 50, 41, 41, 32, 61, 32, 40, 81, 117, 98, 105, 116, 40, 41, 44, 32, 81, 117, 98, 105, 116, 40, 41, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 55, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 40, 113, 115, 41, 32, 61, 32, 40, 81, 117, 98, 105, 116, 40, 41, 44, 32, 81, 117, 98, 105, 116, 40, 41, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 56, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 113, 115, 32, 61, 32, 40, 81, 117, 98, 105, 116, 40, 41, 44, 32, 81, 117, 98, 105, 116, 40, 41, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 57, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 40, 113, 49, 44, 32, 113, 50, 41, 32, 61, 32, 40, 81, 117, 98, 105, 116, 40, 41, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 48, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 117, 115, 101, 32, 40, 113, 49, 44, 32, 113, 50, 44, 32, 113, 51, 41, 32, 61, 32, 40, 81, 117, 98, 105, 116, 40, 41, 44, 32, 40, 81, 117, 98, 105, 116, 40, 41, 44, 32, 81, 117, 98, 105, 116, 40, 41, 41, 41, 32, 123, 125, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 49, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 114, 101, 99, 117, 114, 32, 61, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 49, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 99, 117, 114, 40, 99, 110, 116, 32, 45, 32, 49, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 50, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 116, 117, 112, 108, 101, 32, 61, 32, 40, 49, 44, 32, 40, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 50, 44, 32, 34, 34, 41, 41, 59, 32, 47, 47, 32, 110, 111, 116, 32, 97, 108, 108, 111, 119, 101, 100, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 40, 95, 44, 32, 114, 101, 99, 117, 114, 41, 32, 61, 32, 116, 117, 112, 108, 101, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 99, 117, 114, 40, 99, 110, 116, 32, 45, 32, 49, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 51, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 43, 61, 32, 91, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 50, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 52, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 97, 114, 114, 32, 61, 32, 91, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 52, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 95, 97, 114, 114, 32, 61, 32, 91, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 52, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 53, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 61, 32, 91, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 53, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 54, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 43, 61, 32, 91, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 54, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 55, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 40, 73, 110, 116, 44, 32, 39, 84, 41, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 49, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 60, 45, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 55, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 56, 60, 39, 84, 62, 40, 99, 110, 116, 58, 32, 73, 110, 116, 44, 32, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 112, 121, 114, 105, 103, 104, 116, 32, 40, 99, 41, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 67, 111, 114, 112, 111, 114, 97, 116, 105, 111, 110, 46, 32, 65, 108, 108, 32, 114, 105, 103, 104, 116, 115, 32, 114, 101, 115, 101, 114, 118, 101, 100, 46, 10, 47, 47, 32, 76, 105, 99, 101, 110, 115, 101, 100, 32, 117, 110, 100, 101, 114, 32, 116, 104, 101, 32, 77, 73, 84, 32, 76, 105, 99, 101, 110, 115, 101, 46, 10, 10, 110, 97, 109, 101, 115, 112, 97, 99, 101, 32, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 81, 117, 97, 110, 116, 117, 109, 46, 84, 101, 115, 116, 105, 110, 103, 46, 81, 73, 82, 10, 123, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 71, 101, 116, 82, 97, 110, 100, 111, 109, 66, 111, 111, 108, 40, 115, 101, 101, 100, 32, 58, 32, 73, 110, 116, 41, 32, 58, 32, 66, 111, 111, 108, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 98, 111, 100, 121, 32, 105, 110, 116, 114, 105, 110, 115, 105, 99, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 64, 69, 110, 116, 114, 121, 80, 111, 105, 110, 116, 40, 41, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 84, 101, 115, 116, 83, 104, 111, 114, 116, 67, 105, 114, 99, 117, 105, 116, 105, 110, 103, 32, 40, 41, 32, 56, 32, 40, 66, 111, 111, 108, 44, 32, 66, 111, 111, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 110, 101, 119, 32, 40, 40, 73, 110, 116, 44, 32, 39, 84, 41, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 50, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 46, 46, 32, 49, 32, 60, 45, 32, 91, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 56, 44, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 55, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 91, 48, 93, 40, 99, 110, 116, 32, 45, 32, 49, 44, 32, 97, 114, 103, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 111, 112, 101, 114, 97, 116, 105, 111, 110, 32, 86, 97, 114, 105, 97, 98, 108, 101, 68, 101, 99, 108, 97, 114, 97, 116, 105, 111, 110, 49, 57, 60, 39, 84, 62, 40, 97, 114, 103, 32, 58, 32, 39, 84, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 111, 112, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 41, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 93, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 97, 114, 114, 32, 119, 47, 32, 48, 32, 60, 45, 32, 111, 112, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 67, 111, 112, 121, 65, 110, 100, 85, 112, 100, 97, 116, 101, 65, 114, 114, 97, 121, 49, 50, 60, 39, 84, 62, 32, 40, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 93, 44, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 49, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 44, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 50, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 41, 10, 32, 32, 32, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 93, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 97, 114, 114, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 119, 47, 32, 48, 32, 60, 45, 32, 111, 112, 49, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 119, 47, 32, 49, 32, 60, 45, 32, 111, 112, 50, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 67, 111, 112, 121, 65, 110, 100, 85, 112, 100, 97, 116, 101, 65, 114, 114, 97, 121, 49, 51, 60, 39, 84, 62, 32, 40, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 93, 44, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 49, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 67, 116, 108, 41, 44, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 50, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 41, 10, 32, 32, 32, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 41, 91, 93, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 97, 114, 114, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 119, 47, 32, 48, 32, 60, 45, 32, 111, 112, 49, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 119, 47, 32, 49, 32, 60, 45, 32, 111, 112, 50, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 67, 111, 112, 121, 65, 110, 100, 85, 112, 100, 97, 116, 101, 65, 114, 114, 97, 121, 49, 52, 60, 39, 84, 62, 32, 40, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 91, 93, 44, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 49, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 67, 116, 108, 32, 43, 32, 65, 100, 106, 41, 44, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 50, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 41, 10, 32, 32, 32, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 91, 93, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 97, 114, 114, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 119, 47, 32, 48, 32, 60, 45, 32, 111, 112, 49, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 119, 47, 32, 49, 32, 60, 45, 32, 111, 112, 50, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 67, 111, 112, 121, 65, 110, 100, 85, 112, 100, 97, 116, 101, 65, 114, 114, 97, 121, 49, 53, 60, 39, 84, 62, 32, 40, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 91, 93, 44, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 67, 116, 108, 41, 41, 10, 32, 32, 32, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 91, 93, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 97, 114, 114, 32, 119, 47, 32, 48, 32, 60, 45, 32, 111, 112, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 67, 111, 112, 121, 65, 110, 100, 85, 112, 100, 97, 116, 101, 65, 114, 114, 97, 121, 49, 54, 60, 39, 84, 62, 32, 40, 10, 32, 32, 32, 32, 32, 32, 32, 32, 97, 114, 114, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 91, 93, 44, 10, 32, 32, 32, 32, 32, 32, 32, 32, 111, 112, 32, 58, 32, 40, 73, 110, 116, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 41, 10, 32, 32, 32, 32, 58, 32, 40, 39, 84, 32, 61, 62, 32, 85, 110, 105, 116, 32, 105, 115, 32, 65, 100, 106, 41, 91, 93, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 97, 114, 114, 32, 119, 47, 32, 48, 32, 60, 45, 32, 111, 112, 59, 10, 32, 32, 32, 32, 125, 10, 10, 10, 32, 32, 32, 32, 47, 47, 32, 117, 112, 100, 97, 116, 101, 45, 97, 110, 100, 45, 114, 101, 97, 115, 115, 105, 103, 110, 32, 97, 114, 114, 97, 121, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 85, 112, 100, 97, 116, 101, 65, 110, 100, 82, 101, 97, 115, 115, 105, 103, 110, 49, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 1, 0, 0, 0, 0, 0, 0, 0, 32, 115, 105, 122, 101, 32, 61, 32, 49, 48, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 49, 32, 60, 45, 32, 48, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 85, 112, 100, 97, 116, 101, 65, 110, 100, 82, 101, 97, 115, 115, 105, 103, 110, 50, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 48, 44, 32, 115, 105, 122, 101, 32, 61, 32, 49, 48, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 46, 46, 32, 50, 32, 60, 45, 32, 91, 48, 44, 48, 44, 48, 93, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 85, 112, 100, 97, 116, 101, 65, 110, 100, 82, 101, 97, 115, 115, 105, 103, 110, 51, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 48, 44, 32, 115, 105, 122, 101, 32, 61, 32, 49, 48, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 114, 32, 119, 47, 61, 32, 48, 32, 46, 46, 32, 76, 101, 110, 103, 116, 104, 40, 97, 114, 114, 41, 45, 49, 32, 60, 45, 32, 97, 114, 114, 32, 119, 47, 32, 48, 32, 60, 45, 32, 49, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 85, 112, 100, 97, 116, 101, 65, 110, 100, 82, 101, 97, 115, 115, 105, 103, 110, 52, 32, 40, 41, 32, 58, 32, 85, 110, 105, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 97, 114, 114, 32, 61, 32, 91, 48, 44, 32, 115, 105, 122, 101, 32, 61, 32, 49, 48, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 97, 114, 32, 73, 110, 116, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 40, 100, 44, 32, 95, 41, 32, 61, 32, 97, 114, 103, 33, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 100, 32, 60, 32, 48, 46, 32, 63, 32, 48, 32, 124, 32, 97, 114, 103, 58, 58, 82, 101, 32, 43, 32, 97, 114, 103, 58, 58, 73, 109, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 73, 116, 101, 109, 65, 99, 99, 101, 115, 115, 53, 32, 40, 97, 114, 103, 49, 32, 58, 32, 78, 97, 109, 101, 100, 73, 116, 101, 109, 115, 50, 44, 32, 97, 114, 103, 50, 32, 58, 32, 78, 97, 109, 101, 100, 73, 116, 101, 109, 115, 54, 41, 32, 58, 32, 40, 73, 110, 116, 44, 32, 68, 111, 117, 98, 108, 101, 41, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 40, 100, 44, 32, 40, 95, 44, 32, 105, 109, 41, 41, 32, 61, 32, 97, 114, 103, 49, 33, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 40, 40, 40, 105, 49, 44, 32, 105, 50, 41, 44, 32, 112, 41, 44, 32, 40, 99, 44, 32, 40, 100, 49, 44, 32, 100, 50, 41, 41, 41, 32, 61, 32, 97, 114, 103, 50, 33, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 112, 32, 33, 61, 32, 97, 114, 103, 50, 58, 58, 80, 104, 97, 115, 101, 32, 111, 114, 32, 99, 32, 33, 61, 32, 97, 114, 103, 50, 58, 58, 67, 111, 110, 115, 116, 41, 32, 123, 32, 102, 97, 105, 108, 32, 34, 115, 104, 111, 117, 108, 100, 32, 98, 101, 32, 101, 113, 117, 97, 108, 34, 59, 32, 125, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 40, 100, 32, 43, 32, 97, 114, 103, 49, 58, 58, 82, 101, 32, 43, 32, 105, 49, 32, 45, 32, 105, 50, 44, 32, 100, 49, 32, 42, 32, 100, 50, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 73, 116, 101, 109, 65, 99, 99, 101, 115, 115, 54, 32, 40, 97, 114, 103, 49, 32, 58, 32, 78, 97, 109, 101, 100, 73, 116, 101, 109, 115, 52, 44, 32, 97, 114, 103, 50, 32, 58, 32, 78, 97, 109, 101, 100, 73, 116, 101, 109, 115, 53, 41, 32, 58, 32, 40, 40, 68, 111, 117, 98, 108, 101, 44, 32, 68, 111, 117, 98, 108, 101, 41, 44, 32, 68, 111, 117, 98, 108, 101, 44, 32, 73, 110, 116, 44, 32, 40, 73, 110, 116, 44, 32, 73, 110, 116, 41, 41, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 40, 95, 44, 32, 112, 97, 105, 114, 49, 41, 32, 61, 32, 97, 114, 103, 49, 33, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 108, 101, 116, 32, 40, 112, 97, 105, 114, 50, 44, 32, 95, 41, 32, 61, 32, 97, 114, 103, 50, 33, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 40, 112, 97, 105, 114, 49, 44, 32, 97, 114, 103, 49, 58, 58, 67, 111, 110, 115, 116, 44, 32, 97, 114, 103, 50, 58, 58, 80, 104, 97, 115, 101, 44, 32, 112, 97, 105, 114, 50, 41, 59, 10, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 73, 116, 101, 109, 65, 99, 99, 101, 115, 115, 55, 32, 40, 97, 114, 103, 49, 32, 58, 32, 65, 114, 114, 97, 121, 84, 121, 112, 101, 52, 44, 32, 97, 114, 103, 50, 32, 58, 32, 65, 114, 114, 97, 121, 84, 121, 112, 101, 53, 41, 32, 58, 32, 40, 73, 110, 116, 44, 32, 73, 110, 116, 44, 32, 73, 110, 116, 41, 91, 93, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 76, 101, 110, 103, 116, 104, 40, 97, 114, 103, 49, 58, 58, 78, 97, 109, 101, 41, 32, 33, 61, 32, 76, 101, 110, 103, 116, 104, 40, 97, 114, 103, 50, 58, 58, 78, 97, 109, 101, 41, 41, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 102, 97, 105, 108, 32, 34, 108, 101, 110, 103, 116, 104, 32, 109, 105, 115, 109, 97, 116, 99, 104, 34, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 125, 10, 10, 32, 32, 32, 32, 32, 32, 32, 32, 109, 117, 116, 97, 98, 108, 101, 32, 114, 101, 115, 32, 61, 32, 91, 93, 59, 10, 32, 32, 32, 32, 32, 32, 32, 32, 102, 111, 114, 32, 40, 105, 49, 44, 32, 105, 50, 41, 32, 105, 110, 32, 97, 114, 103, 50, 58, 58, 78, 97, 109, 101, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 115, 101, 116, 32, 114, 101, 115, 32, 43, 61, 32, 91, 40, 105, 49, 44, 32, 105, 50, 44, 32, 97, 114, 103, 49, 58, 58, 78, 97, 109, 101, 91, 76, 101, 110, 103, 116, 104, 40, 114, 101, 115, 41, 93, 41, 93, 59, 10]

Reproduce with:

	cargo fuzz run -O --features=do_fuzz --sanitizer=none compile fuzz/artifacts/compile/crash-329783cbc2fd0828840d6c289adc83a0bc2bb478

Minimize test case with:

	cargo fuzz tmin -O --features=do_fuzz --sanitizer=none compile fuzz/artifacts/compile/crash-329783cbc2fd0828840d6c289adc83a0bc2bb478

────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit status: 77

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: cargo_fuzz::project::FuzzProject::exec_fuzz
   2: cargo_fuzz::main
   3: std::sys_common::backtrace::__rust_begin_short_backtrace
   4: std::rt::lang_start::{{closure}}
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/core/src/ops/function.rs:284:13
   6: std::panicking::try::do_call
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/std/src/panicking.rs:500:40
   7: std::panicking::try
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/std/src/panicking.rs:464:19
   8: std::panic::catch_unwind
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/std/src/panic.rs:142:14
   9: std::rt::lang_start_internal::{{closure}}
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/std/src/rt.rs:148:48
  10: std::panicking::try::do_call
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/std/src/panicking.rs:500:40
  11: std::panicking::try
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/std/src/panicking.rs:464:19
  12: std::panic::catch_unwind
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/std/src/panic.rs:142:14
  13: std::rt::lang_start_internal
             at /rustc/da6b55cc5eaf76ed6acb7dc2f7d611e32af7c9a7/library/std/src/rt.rs:148:20
  14: main
  15: <unknown>
  16: __libc_start_main
  17: _start
```

</details>

<details><summary><b>The commit in <code>main</code> the bug has been found in:</b> Click.</summary>
If the developers fail to repro the bug in the latest <code>main</code> then the commit info below can help them to make sure
that they are using the correct way to repro. If the bug is reproducible in the commit below, but not in latest <code>main</code>,
then the bug is likely fixed already.

```log
commit 6822b1b879b841329f7d5c746e710af4d12dc7f9
Author: Alex Hansen <alex@alex-hansen.com>
Date:   Tue Jul 18 07:46:08 2023 -0700

    Merge branch 'main' into alex/454-2
```

</details>

**Other Info**

- [**Workflow**](https://github.com/microsoft/qsharp/actions/runs/5589902233) (contains the run artifacts).
- **Workflow Agent System Info:** `ubuntu-latest: Linux fv-az573-663 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`.
- **Bug Reporting Timestamp:** 2023.07.18 16:24 UTC (UTC - 8:00 = PST. UTC - 7:00 = PDT).

### PR DESCRIPTION
**Pull request by sezna**
This PR cooks the apostrophe and ident tokens into one new token, `AposIdent`. `AposIdent` represents a generic parameter like `'T`.

closes #407
closes #468

### CODE REVIEW

**Review by kuzminrobin — APPROVED** [review]
Approving to unblock. More approvals recommended.

**Comment by kuzminrobin** [comment]
> Approving to unblock. More approvals recommended.

Looks like it does not help any more. The code owners' approval is still required.

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 1]
```diff
@@ -357,15 +370,26 @@ impl<'a> Lexer<'a> {
...
+                // disallow whitespace and comments after apostrophes
+                // see https://github.com/microsoft/qsharp/issues/407 for context
+                if matches!(
+                    self.tokens.peek().map(|tok| tok.kind),
+                    Some(raw::TokenKind::Whitespace | raw::TokenKind::Comment(_))
+                ) {
+                    Err(Error::UnfinishedGeneric(span))
+                } else {
+                    Ok(TokenKind::Apos)
+                }
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:391]: I wouldn't think of this in terms of the negative cases (it's an error for an Apos to be followed by a Whitespace or Comment). There are lots and lots of negative cases, but there's only one positive case: an Apos token must be followed by an Ident. Let's cook both of them into a single token representing a type parameter name. ([Parse, don't validate.](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/))

This does mean that the name of all type parameters will change downstream to include the `'`, but I think that's fine.

**Review by samarsha — CHANGES_REQUESTED** [review]

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 2]
```diff
@@ -150,7 +151,7 @@ pub(crate) enum TokenKind {
 impl Display for TokenKind {
     fn fmt(&self, f: &mut Formatter) -> fmt::Result {
         match self {
-            TokenKind::Apos => f.write_str("`'`"),
+            TokenKind::AposIdent => f.write_str("`'`"),
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:154]: This is the token name used in error messages. I would be more descriptive, like:

```suggestion
            TokenKind::AposIdent => f.write_str("apostrophe identifier"),
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 3]
```diff
@@ -365,7 +366,11 @@ impl<'a> Lexer<'a> {
                 self.expect(Single::Amp, TokenKind::ClosedBinOp(op))?;
                 Ok(self.closed_bin_op(op))
             }
-            Single::Apos => Ok(TokenKind::Apos),
+            Single::Apos => {
+                self.tokens
+                    .next_if(|t| matches!(t.kind, raw::TokenKind::Ident));
+                Ok(TokenKind::AposIdent)
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:372]: This treats the identifier after the apostrophe as optional, meaning that an apostrophe followed by a non-ident will still be cooked into AposIdent. There is no other token that uses apostrophe, so it should be an error.

**Review by samarsha — CHANGES_REQUESTED** [review]

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 4]
```diff
@@ -51,6 +51,10 @@ pub(crate) enum Error {
     #[error("unrecognized character `{0}`")]
     #[diagnostic(code("Qsc.Lex.UnknownChar"))]
     Unknown(char, #[label] Span),
+
+    #[error("unfinished generic")]
+    #[diagnostic(code("Qsc.Lex.UnfinishedGeneric"))]
+    UnfinishedGeneric(#[label] Span),
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:57]: This should follow the same pattern as the Incomplete and IncompleteEof errors above.

Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:57]: This PR isn’t consistent about whether the token is referred to as an “apostrophe identifier” or a “generic.” I would recommend picking one. The lexer prefers low-level descriptions like apostrophe, while the parser uses high-level descriptions like generic parameter.

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 5]
```diff
@@ -357,15 +371,29 @@ impl<'a> Lexer<'a> {
...
+            Single::Apos => {
+                if matches!(
+                    self.tokens.peek(),
+                    Some(raw::Token {
+                        kind: raw::TokenKind::Ident,
+                        ..
+                    })
+                ) {
+                    self.tokens
+                        .next_if(|t| matches!(t.kind, raw::TokenKind::Ident));
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:391]:
```suggestion
                        .next();
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 6]
```diff
@@ -51,6 +51,14 @@ pub(crate) enum Error {
     #[error("unrecognized character `{0}`")]
     #[diagnostic(code("Qsc.Lex.UnknownChar"))]
     Unknown(char, #[label] Span),
+
+    #[error("expected identifier to complete apostrophe identifier, found {0}")]
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:55]:
```suggestion
    #[error("expected identifier after apostrophe, found {0}")]
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 7]
```diff
@@ -51,6 +51,14 @@ pub(crate) enum Error {
...
+    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifier"))]
+    IncompleteApostropheIdentifier(raw::TokenKind, #[label] Span),
+
+    #[error("expected identifier to complete apostrophe identifier, found EOF")]
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:59]:
```suggestion
    #[error("expected identifier after apostrophe, found EOF")]
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 8]
```diff
@@ -51,6 +51,14 @@ pub(crate) enum Error {
     #[error("unrecognized character `{0}`")]
     #[diagnostic(code("Qsc.Lex.UnknownChar"))]
     Unknown(char, #[label] Span),
+
+    #[error("expected identifier to complete apostrophe identifier, found {0}")]
+    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifier"))]
+    IncompleteApostropheIdentifier(raw::TokenKind, #[label] Span),
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:57]:
```suggestion
    #[diagnostic(code("Qsc.Lex.IncompleteAposIdent"))]
    IncompleteAposIdent(raw::TokenKind, #[label] Span),
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 9]
```diff
@@ -51,6 +51,14 @@ pub(crate) enum Error {
...
+
+    #[error("expected identifier to complete apostrophe identifier, found EOF")]
+    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifierEof"))]
+    IncompleteApostropheIdentifierEof(#[label] Span),
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:61]:
```suggestion
    IncompleteAposIdentEof(#[label] Span),
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 10]
```diff
@@ -357,15 +380,25 @@ impl<'a> Lexer<'a> {
     }
 
     #[allow(clippy::too_many_lines)]
-    fn single(&mut self, single: Single) -> Result<TokenKind, Error> {
+    fn single(&mut self, single: Single, span: Span) -> Result<TokenKind, Error> {
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:383]: `single` doesn't need this parameter. The other incomplete errors use the span of the next token, not the span of the current token.

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 11]
```diff
@@ -51,6 +51,14 @@ pub(crate) enum Error {
...
     #[diagnostic(code("Qsc.Lex.UnknownChar"))]
     Unknown(char, #[label] Span),
+
+    #[error("expected identifier after apostrophe, found {0}")]
+    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifier"))]
+    IncompleteAposIdent(raw::TokenKind, #[label] Span),
+
+    #[error("expected identifier after apostrophe, found EOF")]
+    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifierEof"))]
+    IncompleteAposIdentEof(#[label] Span),
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:61]: nit: Can you move these up so all the `Incomplete*` cases are next to each other?

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 12]
```diff
@@ -44,6 +44,14 @@ pub(crate) enum Error {
     #[diagnostic(code("Qsc.Lex.IncompleteEof"))]
     IncompleteEof(raw::Single, TokenKind, #[label] Span),
 
+    #[error("expected identifier after apostrophe, found {0}")]
+    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifier"))]
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:48]:
```suggestion
    #[diagnostic(code("Qsc.Lex.IncompleteAposIdent"))]
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 13]
```diff
@@ -44,6 +44,14 @@ pub(crate) enum Error {
...
+    IncompleteAposIdent(raw::TokenKind, #[label] Span),
+
+    #[error("expected identifier after apostrophe, found EOF")]
+    #[diagnostic(code("Qsc.Lex.IncompleteApostropheIdentifierEof"))]
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:52]:
```suggestion
    #[diagnostic(code("Qsc.Lex.IncompleteAposIdentEof"))]
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 14]
```diff
@@ -365,7 +376,26 @@ impl<'a> Lexer<'a> {
...
+                        let span = Span { lo: offset, hi };
+                        Err(Error::IncompleteAposIdent(kind, span))
+                    }
+                    None => {
+                        let lo = self.len;
+                        let span = Span { lo, hi: lo };
+                        Err(Error::IncompleteAposIdentEof(span))
+                    }
+                }
+            }
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:398]: I don't think we should just copy/paste this from Lexer::expect - handling any Token is more general than handling only Single tokens, so there should be a way to refactor and share the logic.

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 15]
```diff
@@ -38,11 +38,11 @@ pub(crate) struct Token {
 pub(crate) enum Error {
     #[error("expected `{0}` to complete {1}, found {2}")]
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:39]: The Display for raw::TokenKind already puts ticks around Single.

```suggestion
    #[error("expected {0} to complete {1}, found {2}")]
```

File: compiler/qsc_parse/src/lex/cooked.rs [hunk 16]
```diff
@@ -38,11 +38,11 @@ pub(crate) struct Token {
...
     #[diagnostic(code("Qsc.Lex.Incomplete"))]
-    Incomplete(raw::Single, TokenKind, raw::TokenKind, #[label] Span),
+    Incomplete(raw::TokenKind, TokenKind, raw::TokenKind, #[label] Span),
 
     #[error("expected `{0}` to complete {1}, found EOF")]
```
Comment (samarsha) [inline compiler/qsc_parse/src/lex/cooked.rs:43]:
```suggestion
    #[error("expected {0} to complete {1}, found EOF")]
```

**Comment by samarsha** [comment]
The tests need to be updated, but I think the new spans in the errors are correct.

**Review by samarsha — APPROVED** [review]
