### PR TITLE
Fix to RCA panic when assigning call result to tuple

### LINKED ISSUE #1357: RCA panics when assigning call result to tuple
RCA fails with this specific code snippet:

```qsharp
operation Foo() : (Int, Int) {
    return (1,2);
}

mutable a = 1;
mutable b = 2;

set (a, b) = Foo();
```

**To Reproduce**

Try running this unit test alongside the RCA unit tests:

```rs
#[test]
fn assign_call_result_to_tuple() {
    let mut compilation_context = CompilationContext::default();
    compilation_context.update(
        r#"
        operation Foo() : (Int, Int) {
            return (1,2);
        }

        mutable a = 1;
        mutable b = 2;

        set (a, b) = Foo();

        "#,
    );
    let package_store_compute_properties = compilation_context.get_compute_properties();
    check_last_statement_compute_properties(
        package_store_compute_properties,
        &expect![
            r#"
            ApplicationsGeneratorSet:
                inherent: Quantum: QuantumProperties:
                    runtime_features: RuntimeFeatureFlags(0x0)
                    value_kind: Element(Static)
                dynamic_param_applications: <empty>"#
        ],
    );
}

```

Actual:

```
thread 'assign_call_result_to_tuple' panicked at compiler/qsc_rca/src/core.rs:1394:21:
expected a tuple
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
   2: qsc_rca::core::Analyzer::update_locals_compute_kind
             at ./src/core.rs:1394:21
   3: qsc_rca::core::Analyzer::analyze_expr_assign
             at ./src/core.rs:148:36
   4: <qsc_rca::core::Analyzer as qsc_fir::visit::Visitor>::visit_expr
             at ./src/core.rs:1516:17
   5: <qsc_rca::core::Analyzer as qsc_fir::visit::Visitor>::visit_stmt
             at ./src/core.rs:1671:17
   6: qsc_rca::core::Analyzer::analyze_package_internal
             at ./src/core.rs:998:13
   7: qsc_rca::core::Analyzer::analyze_package
             at ./src/core.rs:54:9
   8: qsc_rca::analyzer::Analyzer::analyze_package
             at ./src/analyzer.rs:61:9
   9: qubits::test_utils::CompilationContext::update
             at ./tests/test_utils.rs:65:35
  10: qubits::assign_call_result_to_tuple
             at ./tests/qubits.rs:16:5
  11: qubits::assign_call_result_to_tuple::{{closure}}
             at ./tests/qubits.rs:14:33
  12: core::ops::function::FnOnce::call_once
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test assign_call_result_to_tuple ... FAILED

failures:

failures:
    assign_call_result_to_tuple

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.86s

```

### PR DESCRIPTION
**Pull request by cesarzc**
This change fixes #1357.

### CODE REVIEW

File: compiler/qsc_rca/tests/assigns.rs [hunk 1]
```diff
@@ -132,3 +132,102 @@ fn check_rca_for_dynamic_double_assign_to_local() {
         ],
     );
 }
+
+#[test]
+fn chec_rca_for_assign_call_result_to_tuple() {
```
Comment (swernli) [inline compiler/qsc_rca/tests/assigns.rs:137]: The test for call results are great! Do we also need some for a variable? As in:
```qsharp
let x = Foo();
mutable a = 1;
mutable b = 2;
set (a, b) = x;
```

**Review by swernli — APPROVED** [review]

File: compiler/qsc_rca/tests/assigns.rs (hunk 1 above)
Comment (cesarzc) [reply compiler/qsc_rca/tests/assigns.rs:137]: It wouldn't hurt to add this test, I'll add it!

Comment (cesarzc) [reply compiler/qsc_rca/tests/assigns.rs]: More tests added.
