### PR TITLE
[Unitary Hack] Save Python qsharp-widgets RE output to PNG

### LINKED ISSUE #1063: Add ability to save the Resource Estimator space-time diagram as a file (png/jpg/svg)
This would not work in VS Code but we can consider Jupyter notebook and other scenarios

### PR DESCRIPTION
**Pull request by nirajvenkat**
Submission for Unitary Hack issue: fixes #1063 

This change adds the ability to save the resource estimates diagram locally as a PNG. For this I added a new dependency called `html2canvas` that takes a DOM and renders it to an image. This currently works only on IPython `qsharp-widgets`, could be extended to the VSCode version. 

Additionally we take into account the color theme within VSCode (which is provided in the stylesheet `qsharp-ux.css`) and this is passed in as the background color for rendering. Tested on (dark/light) Modern VSCode themes.

https://github.com/microsoft/qsharp/assets/3744263/898de6d9-fba4-4fea-b729-a3bb698dc51c

~Current issues:~
- ~This button is placeholder, nicer version: https://github.com/microsoft/vscode-notebook-renderers/pull/118~
- ~Saved imaged is slightly truncated at the bottom~

### CODE REVIEW

**Comment by nirajvenkat** [comment]
@microsoft-github-policy-service agree

**Comment by billti** [comment]
We are _very_ conservative in this project on taking new dependencies. I see you added one called 'html2canvas'. Looking at that project I can see it has over 900 open issues, hasn't had a commit for 2 years, and the README states 

  "_The script is still in a very experimental state, so I don't recommend using it in a production environment nor start building applications with it yet, as there will be still major changes made_".

Based on the above, I'm hesitant to take a change which adds this dependency.

**Comment by nirajvenkat** [comment]
Would it be ok to add a different dependency? [This one](https://github.com/bubkoo/html-to-image) for example, is more active and has less outstanding issues.

Also the way I have been doing development is to first run the watcher using `npm run dev`, make some changes, after which I switch to a jupyter notebook (also in VSCode) and must reload the kernel to get the newest version built by the watcher, then re-run the cell. Is there any way to attach a debugger or to view print logs?

**Comment by billti** [comment]
We use SVG a lot, as well as dynamic DOM nodes (via Preact) for our widgets, so issues such as https://github.com/bubkoo/html-to-image/issues/425, https://github.com/bubkoo/html-to-image/issues/463, and https://github.com/bubkoo/html-to-image/issues/392 could come into play (I've been optimizing some SVG sizes via def/use lately, so likely to be even more of an issue going forward).

Sadly again, the project seems unmaintained. The last release was 18 months ago, and all issues since just have an automated response and no follow up (including this one 🤣 https://github.com/bubkoo/html-to-image/issues/455)

**Comment by nirajvenkat** [comment]
> Also the way I have been doing development is to first run the watcher using npm run dev, make some changes, after which I switch to a jupyter notebook (also in VSCode) and must reload the kernel to get the newest version built by the watcher, then re-run the cell. Is there any way to attach a debugger or to view print logs?

@minestarks @ivanbasov Do you have any pointers on a faster way to work on `qsharp-widgets`?

**Comment by nirajvenkat** [comment]
Fixed prior issues, ready for review.

File: npm/qsharp/ux/saveImageUtil.tsx
Comment (minestarks) [inline npm/qsharp/ux/saveImageUtil.tsx:1]: Is the point of this file to render the HTML elements inside a SVG, and then render that inside a Canvas so that we can save it as PNG? 

If that's the case, I'm not sure all this is necessary. We actually just want an image of the ScatterChart image (see scatterChart.tsx),  and that's already a SVG. 

I think it's ok if the "save as image" button only applies to the ScatterChart and only captures that SVG as image. Then hopefully you can remove all this code which renders HTML as a foreignObject. 

Hopefully, not having to take a screenshot of the whole document will also take care of the "extra whitespace on the sides" problem as well.

**Review by minestarks — CHANGES_REQUESTED** [review]
Thank you!! This works great functionally but I have some style / UI requests.

File: npm/qsharp/ux/estimatesOverview.tsx [hunk 1]
```diff
@@ -306,8 +329,31 @@ export function EstimatesOverview(props: {
         </>
       ) : (
         <>
-          {getResultTable()}
-          {getScatterChart()}
+          <button
+            role="button"
+            onClick={handleSaveImage}
+            className={"qs-estimatesOverview-saveIcon"}
+            style="position: absolute; top: 5px; right: 5px;"
```
[the remark this answers is not in the document]
Comment (nirajvenkat) [reply npm/qsharp/ux/estimatesOverview.tsx:336]: 1. Resolved.
2. Removed the extra whitespace by moving button from `estimatesOverview` to the `scatterChart` component, where it is able to reference the inner svg div.

File: npm/qsharp/ux/estimatesOverview.tsx
[the remark this answers is not in the document]
Comment (nirajvenkat) [reply npm/qsharp/ux/estimatesOverview.tsx:1]: 1. Resolved.
2. Removed the extra whitespace by moving button from estimatesOverview to the scatterChart component, where it is able to reference the inner svg div.

File: npm/qsharp/ux/saveImageUtil.tsx [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+    .then(encodeURIComponent)
+    .then((html) => `data:image/svg+xml;charset=utf-8,${html}`);
+}
+
+export async function nodeToDataURI(
+  node: HTMLElement,
+  width: number,
+  height: number,
+): Promise<string> {
+  const xmlns = "http://www.w3.org/2000/svg";
```
[the remark this answers is not in the document]
Comment (nirajvenkat) [reply npm/qsharp/ux/saveImageUtil.tsx:55]: Using HTTPS is not possible with this link. I assume that is the proposed fix.

File: npm/qsharp/ux/saveImageUtil.tsx
Comment (nirajvenkat) [reply npm/qsharp/ux/saveImageUtil.tsx:1]: I am making a test commit to show my progress. We have two paths, SVG and PNG, toggled by `isVSCodeEnv`. Here are my thoughts.

SVG:
image
- Does not suffer from truncation issues, and we do not pass in a background color. But we suffer from styling issues (click the above image for example).
- Works great on regular Jupyter notebook in the browser, but I am running into an issue on VS Code where the button does nothing. I cannot figure out how to attach a debugger to inspect further ([these steps](https://github.com/microsoft/qsharp/pull/1604#issuecomment-2145692207) did not work for me).
- I know saving to SVG is possible, it works well with [this extension](https://github.com/Microsoft/vscode-notebook-renderers), where we get the option to save as SVG or PDF. Not sure how their code works yet. Here is a snippet that uses their extension:
```python
from IPython.display import SVG
SVG(url='https://upload.wikimedia.org/wikipedia/commons/8/84/Example.svg')
```

PNG:
image
- Involves rendering first to a Canvas. But works with all themes and both browser + VS Code.
- Image is getting truncated at the bottom, trying to figure out why. My current workaround is to pass in a padded height into nodeToDataURI. If we use svgToDataURI directly, image gets truncated again.

Comment (minestarks) [reply npm/qsharp/ux/saveImageUtil.tsx:1]: @nirajvenkat thanks for investigating this. Just letting you know I'll get back to you by tomorrow on this so you can finish by the hackathon deadline.

My first instinct is to say "go with PNG and apply the padded height hack", but I want to test a little further. Thanks.

**Comment by nirajvenkat** [comment]
@minestarks Not sure if I can finish up in time for UH submission, so to speed thing up I have proposed commit 6ef794fa396d0faae8b117056a1de59e8cde3f53. This would be saving to PNG, and a simpler API for the UI side that takes in the React RefObject and optionally a filename and does the rest.

File: npm/qsharp/ux/saveImageUtil.tsx
Comment (nirajvenkat) [reply npm/qsharp/ux/saveImageUtil.tsx:1]: Going to resolve this to allow the automated workflow.

File: npm/qsharp/ux/scatterChart.tsx [hunk 3]
```diff
@@ -105,7 +107,7 @@ export function ScatterChart(props: {
     const centerX = (pointRect.left + pointRect.right) / 2;
     const divRect = topDiv.getBoundingClientRect();
     tooltip.style.left = `${centerX - divRect.left - halfWidth}px`;
-    tooltip.style.top = `${centerY - divRect.top + 12}px`;
+    tooltip.style.top = `${centerY - divRect.top}px`; // + 12}px`;
```
Comment (minestarks) [inline npm/qsharp/ux/scatterChart.tsx:110]: What was this change for?

File: npm/qsharp/ux/scatterChart.tsx [hunk 4]
```diff
@@ -154,6 +156,12 @@ export function ScatterChart(props: {
   }
   const selectedPoint = getSelectedPointData();
 
+  const saveRef = createRef();
+
+  const handleSaveImage = async () => {
+    saveRefToImage(saveRef);
+  };
```
Comment (minestarks) [inline npm/qsharp/ux/scatterChart.tsx:163]: You'll probably want to use `useRef` here instead (as we do in other places) .

```suggestion
  const saveRef = useRef<SVGSVGElement>(null);

  const handleSaveImage = async () => {
    saveToImage(saveRef.current!);
  };
```

Also would recommend calling  `.current` here at the call site, so that `saveToImage()` takes the element instead of the ref. Makes the code boundaries cleaner, IMO. (I renamed `saveRefToImage() -> saveToImage()` to make it clear it doesn't take a ref)

File: npm/qsharp/ux/scatterChart.tsx (hunk 3 above)
Comment (nirajvenkat) [reply npm/qsharp/ux/scatterChart.tsx:110]: Apologies, forgot to revert. Was trying to find a way around the padding hack.

**Comment by minestarks** [comment]
We should be good on the hackathon deadline. This is so close, but it doesn't work in VS Code for me. Probably because VS Code webview doesn't support `window.open`? Feel free to take a stab at implementing proper VS Code extension support (possibly using `showSaveDialog` ?) but that may be tricky and not required for this PR. 

In the meantime please disable it for VS Code (consider taking [this commit to pass an `allowSaveImage` flag ](https://github.com/microsoft/qsharp/commit/dab55c386bcc3708bb6cf12bf3a4fe45d8912630)) . 

Once VS Code is good to go and the other comments are resolved I'll merge this. We're OK on the deadline.

File: npm/qsharp/ux/scatterChart.tsx (hunk 4 above)
Comment (nirajvenkat) [reply npm/qsharp/ux/scatterChart.tsx:163]: I tried `useRef` instead of `createRef` earlier and ran into an error. So I looked around and found [this post](https://stackoverflow.com/a/61638527) which shows how they are related. This is why I chose to use `createRef` which would also avoid type casting which we would need to do otherwise. Quick and ugly way to do this (at the call site or somewhere else:
```
    saveToImage(saveRef.current! as unknown as HTMLElement);
```
We cannot cast directly from `SVGSVGElement` as it does not inherit from `HTMLElement`. However, this code smells so I found an overly complicated route that uses a `DOMParser` to convert to string first, then appends to a newly created `HTMLElement`.

Overall I suggest we continue to use `createRef`, it does not have these issues.

**Comment by nirajvenkat** [comment]
Is it possible for you to merge those changes on your end?

File: npm/qsharp/ux/estimatesPanel.tsx [hunk 5]
```diff
@@ -14,6 +14,7 @@ export function EstimatesPanel(props: {
   runNames: string[];
   calculating: boolean;
   onRowDeleted: (rowId: string) => void;
+  allowSaveImage?: boolean;
```
Comment (nirajvenkat) [inline npm/qsharp/ux/estimatesPanel.tsx:17]: Here we have a `?` on `allowSaveImage`. Should this be added to `allowSaveImage` in the other files?

**Comment by nirajvenkat** [comment]
@minestarks I was thinking that based on the below setting, it should have been okay for you to commit directly to this branch. Not sure what the convention is.
image
In any case this merge was possible on my end. Tested it out by building VSIX package. The button does not show up at all, is this expected?

File: npm/qsharp/ux/estimatesPanel.tsx (hunk 5 above)
Comment (minestarks) [reply npm/qsharp/ux/estimatesPanel.tsx:17]: I think this is alright - I like optional properties when there's more than one caller (so that we don't have to update all callers) , but with these components there's really only one caller, so there's not much point to it.

File: npm/qsharp/ux/scatterChart.tsx (hunk 4 above)
Comment (minestarks) [reply npm/qsharp/ux/scatterChart.tsx]: Couldn't `saveToImage` just take a `SVGSVGElement` directly? There's really not a big need to make it that generic. I'm still a bit iffy about using `createRef` (personally having a strong bias towards consistency).

I agree about wanting to avoid the cast. If there's no other way to make it work it's ok.

**Comment by minestarks** [comment]
> @minestarks I was thinking that based on the below setting, it should have been okay for you to commit directly to this branch. Not sure what the convention is.

@nirajvenkat sorry, it just didn't occur to me that I could push to your branch. Glad you were able to pull the changes regardless

**Review by minestarks — APPROVED** [review]
Please consider the `useRef` suggestion if you can make it work - otherwise looks good. Thanks for the contribution!

File: npm/qsharp/ux/scatterChart.tsx (hunk 4 above)
Comment (nirajvenkat) [reply npm/qsharp/ux/scatterChart.tsx]: I don't know of another way, tried casting `SVGSVGElement` to `Element` but it lacks a `style` prop which belongs to `HTMLElement`. This prop is required when we clone the style.

File: npm/qsharp/ux/saveImageUtil.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (billti) [reply npm/qsharp/ux/saveImageUtil.tsx:55]: That's an automated warning. Just ignore it. Obviously doesn't apply when it's just a namespace and not a link.

**Comment by nirajvenkat** [comment]
I am investigating an issue with this branch where the UI is flickering when trying to interact with the points on the graph. Specifically the tooltip that appears when you hover over points keeps flickering. I have a hunch on what it may be but will continue to investigate tomorrow.
